In [1]:
import re
import pandas as pd
import time
import numpy as np
import matplotlib.pyplot as plt
import os
import seaborn as sns

### Reading in the Data

In [2]:
race = 'TOR330'

In [3]:
TOR330_dem = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/Clean 100x100trail Data/{race}_dem.xlsx')

In [4]:
TOR330_dem['Bib'][(TOR330_dem['Year'] == 2022) &
               (TOR330_dem['Retired'] == 'Bosses')].nunique()

0

In [5]:
TOR330_dem.groupby( ['Year','Status1'] )['Status1' ].count()

Year  Status1
2021  DNF                             281
      Finished at Courmayeur          431
2022  DNF                             363
      Finished at Bosses               88
      Finished at Courmayeur          408
      Finished at Rifugio Frassati    101
2023  DNF                             584
      Finished at Courmayeur          622
2024  DNF                             562
      Finished at Courmayeur          533
2025  DNF                             397
      Finished at Courmayeur          744
Name: Status1, dtype: int64

In [8]:
TOR330_dem.groupby(['Retired_Stage','Retired', 'Retired_Detail'])['PK'].count()

Retired_Stage  Retired                  Retired_Detail
DNS            Start                    Start                      138
Stage 1        Baite Youlaz             Baite Youlaz                 2
               La Thuile                La Thuile                   47
               Planaval                 Planaval                    35
               Rifugio Deffeyes         Rifugio Deffeyes            62
               Valgrisenche             Valgrisenche IN            153
                                        Valgrisenche OUT            45
Stage 2        Chalet Epee              Chalet Epee                 37
               Cogne                    Cogne IN                    83
                                        Cogne OUT                   97
               Eaux Rousse              Eaux Rousse                231
               Rhemes-Notre-Dame        Rhemes-Notre-Dame          168
               Rifugio Sella            Rifugio Sella               23
Stage 3        Chardonney               Chardonney                  25
               Donnas                   Donnas IN                   37
                                        Donnas OUT                  51
               Goilles                  Goilles                     14
               Pontboset                Pontboset                    8
               Rifugio Dondena          Rifugio Dondena             16
Stage 4        Col della Vecchia        Col della Vecchia           41
               Gressoney                Gressoney IN                96
                                        Gressoney OUT               85
               Lago Chiaro              Lago Chiaro                 18
               Loo                      Loo                         27
               Niel La Gruba            Niel La Gruba              146
               Perloz                   Perloz                      31
               Rifugio Coda             Rifugio Coda                43
               Rifugio della Barma      Rifugio della Barma         65
               Sassa                    Sassa                       23
Stage 5        Champoluc                Champoluc                   46
               Rifugio Alpenzu          Rifugio Alpenzu             23
               Rifugio Grand Tournalin  Rifugio Grand Tournalin      5
               Valtournenche            Valtournenche IN             9
                                        Valtournenche OUT           15
Stage 6        Bivacco R. Clermont      Bivacco R. Clermont         27
               Bruson Arp               Bruson Arp                   8
               Ollomont                 Ollomont IN                 20
                                        Ollomont OUT                21
               Oyace                    Oyace                       62
               Rifugio Barmasse         Rifugio Barmasse            11
               Rifugio Cuney            Rifugio Cuney                6
               Rifugio Magià            Rifugio Magià               36
               Vareton                  Vareton                     11
Stage 7        Bosses                   Bosses                      11
               Monte de la Saxe         Monte de la Saxe             1
               Pas Entre Deux Sauts     Pas Entre Deux Sauts         2
               Ponteille Desot          Ponteille Desot             11
               Rifugio Champillon       Rifugio Champillon          12
               Rifugio Frassati         Rifugio Frassati             3
Name: PK, dtype: int64

In [6]:
# lifebase_cut_offs_df = pd.read_excel(f'{race} Data/4. TOR330 Timetable Data/{race}_lifebase_cut_offs_df.xlsx')

# # # # Convert integer seconds to timedelta
# lifebase_cut_offs_df['Lifebase Duration'] = pd.to_timedelta(lifebase_cut_offs_df['Lifebase Duration_seconds'], unit='s')

# # # # Convert integer seconds to timedelta
# lifebase_cut_offs_df['Running Total Lifebase Duration'] = pd.to_timedelta(lifebase_cut_offs_df['Running Total Lifebase Duration_seconds'], unit='s')

# lifebase_cut_offs_df

### Read in Individual Data

In [16]:
lifebase_bib_df = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/Clean 100x100trail Data/{race}_lifebase_bib_df.xlsx')

In [7]:
checkpoints_bib_df = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/Clean 100x100trail Data/{race}_checkpoints_bib_df.xlsx')

In [9]:
all_aid_station_bib_df = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/Clean 100x100trail Data/{race}_all_aid_station_bib_df.xlsx')

In [47]:
# bib_df_datasets =[ checkpoints_bib_df, all_aid_station_bib_df, lifebase_bib_df]
# for bib_df in bib_df_datasets:
#     bib_df = bib_df.merge(
#             TOR330_dem[['PK', 'Name','Status1']],
#             on=['PK'],
#             how='left')
# print(bib_df[(bib_df['PK'] == 'TOR330_2023_1321')])

print(TOR330_dem[(TOR330_dem['PK'] == 'TOR330_2023_1321')])

                    PK  Year    Race Name   Bib  Sex Nationality Category  \
2844  TOR330_2023_1321  2023  TOR330  NaN  1321  NaN         NaN      NaN

      Status Status1   Wave  Duration_seconds Retired Finish Category  \
2844   False     DNF  Wave2               NaN  Donnas             NaN

     Retired_Detail  Missed Last Checkpoint  Missed Diff  Missed Diff_seconds  \
2844      Donnas IN                   False          NaN                  NaN

     Retired_Stage
2844       Stage 3

In [46]:
TOR330_dem[(TOR330_dem['Name'].isna())]

,PK,Year,Race,Name,Bib,Sex,Nationality,Category,Status,Status1,Wave,Duration_seconds,Retired,Finish Category,Retired_Detail,Missed Last Checkpoint,Missed Diff,Missed Diff_seconds,Retired_Stage
611,TOR330_2021_3,2021,TOR330,NaN,3,NaN,NaN,NaN,False,DNF,No Wave in 2021,NaN,Cogne,NaN,Cogne OUT,False,NaN,NaN,Stage 2
612,TOR330_2021_14,2021,TOR330,NaN,14,NaN,NaN,NaN,False,DNF,No Wave in 2021,NaN,Cogne,NaN,Cogne OUT,False,NaN,NaN,Stage 2
613,TOR330_2021_22,2021,TOR330,NaN,22,NaN,NaN,NaN,False,DNF,No Wave in 2021,NaN,Donnas,NaN,Donnas OUT,False,NaN,NaN,Stage 3
614,TOR330_2021_67,2021,TOR330,NaN,67,NaN,NaN,NaN,False,DNF,No Wave in 2021,NaN,Valgrisenche,NaN,Valgrisenche OUT,False,NaN,NaN,Stage 1
615,TOR330_2021_86,2021,TOR330,NaN,86,NaN,NaN,NaN,False,DNF,No Wave in 2021,NaN,Valgrisenche,NaN,Valgrisenche IN,False,NaN,NaN,Stage 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5109,TOR330_2025_1529,2025,TOR330,NaN,1529,NaN,NaN,NaN,False,DNF,Wave2,NaN,Cogne,NaN,Cogne OUT,False,NaN,NaN,Stage 2
5110,TOR330_2025_1532,2025,TOR330,NaN,1532,NaN,NaN,NaN,False,DNF,Wave2,NaN,Valgrisenche,NaN,Valgrisenche IN,False,NaN,NaN,Stage 1
5111,TOR330_2025_1539,2025,TOR330,NaN,1539,NaN,NaN,NaN,False,DNF,Wave2,NaN,Valgrisenche,NaN,Valgrisenche IN,False,NaN,NaN,Stage 1
5112,TOR330_2025_1541,2025,TOR330,NaN,1541,NaN,NaN,NaN,False,DNF,Wave2,NaN,Gressoney,NaN,Gressoney OUT,False,NaN,NaN,Stage 4
5113,TOR330_2025_1579,2025,TOR330,NaN,1579,NaN,NaN,NaN,False,DNF,Wave2,NaN,Valgrisenche,NaN,Valgrisenche IN,False,NaN,NaN,Stage 1

In [49]:
print(TOR330_dem[(TOR330_dem['PK'] == 'TOR330_2023_1321')])

                    PK  Year    Race Name   Bib  Sex Nationality Category  \
2844  TOR330_2023_1321  2023  TOR330  NaN  1321  NaN         NaN      NaN

      Status Status1   Wave  Duration_seconds Retired Finish Category  \
2844   False     DNF  Wave2               NaN  Donnas             NaN

     Retired_Detail  Missed Last Checkpoint  Missed Diff  Missed Diff_seconds  \
2844      Donnas IN                   False          NaN                  NaN

     Retired_Stage
2844       Stage 3

In [48]:
print(checkpoints_bib_df[(checkpoints_bib_df['PK'] == 'TOR330_2023_1321')])

                     PK  Year    Race   Bib   Wave           Checkpoint  \
54860  TOR330_2023_1321  2023  TOR330  1321  Wave2                Start
54861  TOR330_2023_1321  2023  TOR330  1321  Wave2            La Thuile
54862  TOR330_2023_1321  2023  TOR330  1321  Wave2      Valgrisenche IN
54863  TOR330_2023_1321  2023  TOR330  1321  Wave2     Valgrisenche OUT
54864  TOR330_2023_1321  2023  TOR330  1321  Wave2          Eaux Rousse
54865  TOR330_2023_1321  2023  TOR330  1321  Wave2             Cogne IN
54866  TOR330_2023_1321  2023  TOR330  1321  Wave2            Cogne OUT
54867  TOR330_2023_1321  2023  TOR330  1321  Wave2            Donnas IN
54868  TOR330_2023_1321  2023  TOR330  1321  Wave2           Donnas OUT
54869  TOR330_2023_1321  2023  TOR330  1321  Wave2  Rifugio della Barma
54870  TOR330_2023_1321  2023  TOR330  1321  Wave2        Niel La Gruba
54871  TOR330_2023_1321  2023  TOR330  1321  Wave2         Gressoney IN
54872  TOR330_2023_1321  2023  TOR330  1321  Wave2        Gressoney OUT
54873  TOR330_2023_1321  2023  TOR330  1321  Wave2            Champoluc
54874  TOR330_2023_1321  2023  TOR330  1321  Wave2     Valtournenche IN
54875  TOR330_2023_1321  2023  TOR330  1321  Wave2    Valtournenche OUT
54876  TOR330_2023_1321  2023  TOR330  1321  Wave2                Oyace
54877  TOR330_2023_1321  2023  TOR330  1321  Wave2          Ollomont IN
54878  TOR330_2023_1321  2023  TOR330  1321  Wave2         Ollomont OUT
54879  TOR330_2023_1321  2023  TOR330  1321  Wave2               FINISH

                             Stage           Timestamp  Duration_seconds  \
54860                      Stage 1 2023-09-10 12:00:00               NaN
54861                      Stage 1 2023-09-10 16:21:13           15673.0
54862                      Stage 1 2023-09-11 02:59:33           38300.0
54863   Time Spent in Valgrisenche 2023-09-11 04:18:13            4720.0
54864                      Stage 2 2023-09-11 16:27:10           43737.0
54865                      Stage 2 2023-09-12 04:17:39           42629.0
54866          Time Spent in Cogne 2023-09-12 05:09:01            3082.0
54867                      Stage 3 2023-09-12 17:18:56           43795.0
54868         Time Spent in Donnas                 NaT               NaN
54869                      Stage 4                 NaT               NaN
54870                      Stage 4                 NaT               NaN
54871                      Stage 4                 NaT               NaN
54872      Time Spent in Gressoney                 NaT               NaN
54873                      Stage 5                 NaT               NaN
54874                      Stage 5                 NaT               NaN
54875  Time Spent in Valtournenche                 NaT               NaN
54876                      Stage 6                 NaT               NaN
54877                      Stage 6                 NaT               NaN
54878       Time Spent in Ollomont                 NaT               NaN
54879                      Stage 7                 NaT               NaN

       Running Total Duration_seconds  Banking Time_seconds  \
54860                             0.0                   NaN
54861                         15673.0                4127.0
54862                         53973.0               14427.0
54863                         58693.0               16907.0
54864                        102430.0               18170.0
54865                        145059.0                6141.0
54866                        148141.0               10259.0
54867                        191936.0               31264.0
54868                             NaN                   NaN
54869                             NaN                   NaN
54870                             NaN                   NaN
54871                             NaN                   NaN
54872                             NaN                   NaN
54873                             NaN                   NaN
54874                             NaN                   NaN
54875                             NaN                   NaN
54876                             NaN                   NaN
54877                             NaN                   NaN
54878                             NaN                   NaN
54879                             NaN                   NaN

      Missed Checkpoint Allocated Time
54860            Within Allocated Time
54861            Within Allocated Time
54862            Within Allocated Time
54863            Within Allocated Time
54864            Within Allocated Time
54865           Outside Allocated Time
54866            Within Allocated Time
54867            Within Allocated Time
54868            Within Allocated Time
54869            Within Allocated Time
54870            Within Allocated Time
54871            Within Allocated Time
54872            Within Allocated Time
54873            Within Allocated Time
54874            Within Allocated Time
54875            Within Allocated Time
54876            Within Allocated Time
54877            Within Allocated Time
54878            Within Allocated Time
54879            Within Allocated Time

In [ ]:
# # making duration hours 
# datasets = [checkpoints_bib_df, lifebase_bib_df, all_aid_station_bib_df,  TOR330_dem]
# for df in datasets:
#     df['Duration_hours'] = df['Duration_seconds']/ 3600

In [30]:
lifebase_bib_df#.columns #[lifebase_bib_df['Name'] == 'Jonathan Smith']

Index(['PK', 'Year', 'Race', 'Bib', 'Wave', 'Lifebase', 'Stage', 'Timestamp',
       'Duration_seconds', 'Running Total Duration_seconds',
       'Banking Time_seconds', 'Missed Lifebase Allocated Time'],
      dtype='object')

### Getting Average and Median time for lifebases

In [19]:
Stage1 = [ 'Start', 'Baite Youlaz', 'La Thuile', 'Rifugio Deffeyes',\
          'Planaval', 'Valgrisenche IN']
Stage2 = [ 'Valgrisenche OUT', 'Chalet Epee',\
          'Rhemes-Notre-Dame', 'Eaux Rousse', 'Rifugio Sella', 'Cogne IN']
Stage3 = [  'Cogne OUT', 'Goilles', 'Rifugio Dondena', 'Chardonney', 'Pontboset','Donnas IN']
Stage4 = [  'Donnas OUT', 'Perloz', 'Sassa', 'Rifugio Coda', \
          'Rifugio della Barma', 'Lago Chiaro', 'Col della Vecchia',\
          'Niel La Gruba', 'Loo', 'Gressoney IN']
Stage5 = [  'Gressoney OUT', 'Rifugio Alpenzu', 'Champoluc' ,\
          'Rifugio Grand Tournalin', 'Valtournenche IN']
Stage6 = [   'Valtournenche OUT', 'Rifugio Barmasse', 'Vareton',\
          'Rifugio Magià', 'Rifugio Cuney', 'Bivacco R. Clermont', 'Oyace', \
          'Bruson Arp', 'Ollomont IN']    
Stage7 = [ 'Ollomont OUT', 'Rifugio Champillon', 'Ponteille Desot',\
          'Bosses', 'Rifugio Frassati', 'Pas Entre Deux Sauts',\
          'Monte de la Saxe', 'FINISH']


stages =[ Stage1, Stage2, Stage3, Stage4, Stage5, Stage6, Stage7]
stages_str =[ 'Stage 1', 'Stage 2', 'Stage 3', 'Stage 4', 'Stage 5', 'Stage 6', 'Stage 7']
lifebase_time_spent = ['Valgrisenche OUT','Cogne OUT','Donnas OUT','Gressoney OUT','Valtournenche OUT','Ollomont OUT']

In [20]:
def creating_time_stats(df, column, category_order):
    
    df_merge = df.merge(
        TOR330_dem[['PK', 'Finish Category']],
        on=['PK'],
        how='left')


    df_merge['Duration_seconds'][df_merge['Duration_seconds']  <= 0] = np.nan

    stats_df = df_merge.groupby(['Finish Category', column])['Duration_seconds'].describe().reset_index(drop = False)


    stats_df[[ 'mean', 'std', 'min', '25%',
           '50%', '75%', 'max']] = stats_df[[ 'mean', 'std', 'min', '25%',
           '50%', '75%', 'max']].round(0)

    # Set 'Finish Category' as a categorical column with the defined order
    stats_df[column] = pd.Categorical(
        stats_df[column],
        categories=category_order,
        ordered=True)
    
    stats_df = stats_df.sort_values(by=column, ascending = True)
    
    

    for finish_category in df_merge['Finish Category'].unique():
        print(finish_category)
        stats_df.loc[
                (stats_df['Finish Category'] == finish_category), 'running_total_mean_seconds'
            ] =     stats_df.loc[
                (stats_df['Finish Category'] == finish_category), 'mean'
            ].cumsum()


        stats_df.loc[
                (stats_df['Finish Category'] == finish_category), 'running_total_median_seconds'
            ] =     stats_df.loc[
                (stats_df['Finish Category'] == finish_category), '50%'
            ].cumsum()


    stats_df = stats_df[['Finish Category', column,
            'count', 'mean', '50%', 'std', 'min', 'max', 
            'running_total_mean_seconds', 'running_total_median_seconds']]


    stats_df = stats_df.rename(columns={'count': f'Count_Finish_Category_{column}_seconds',
                                      'mean': f'Mean_Finish_Category_{column}_seconds',
                                      'std': f'STD_Finish_Category{column}t_seconds',
                                      '50%': f'Median_Finish_Category_{column}_seconds',
                                      'min': f'Min_Finish_Category_{column}_seconds', 
                                      'max': f'Max_Finish_Category_{column}_seconds'})
    stats_df = stats_df[stats_df[column] != 'Start']

    
    
    
    for stage,  stage_str in zip(stages, stages_str):
        stats_df.loc[stats_df[column].isin(stage), 'Stage'] = f'{stage_str}'
        
    for lifebase in lifebase_time_spent:
        lifebase_split = lifebase.split(' OUT')[0] 
        stats_df.loc[stats_df[column] == lifebase, 'Stage'] = f'Time Spent in {lifebase_split}'


    stats_df.to_excel(f'{race} Data/5. Clean Data for Data Visualisation/Schedule Splits/{race}_{column}_duration_mean_median_stats_df.xlsx', index = False)

#     print(stats_df[stats_df['Finish Category'] == 'Sub-130'])
    return stats_df

In [21]:
lifebase_stats_df = creating_time_stats(df = lifebase_bib_df, 
                    column = 'Lifebase', 
                    category_order = ['Start','Valgrisenche IN','Valgrisenche OUT',
                            'Cogne IN',  'Cogne OUT',
                            'Donnas IN', 'Donnas OUT', 
                            'Gressoney IN','Gressoney OUT',
                            'Valtournenche IN','Valtournenche OUT', 
                            'Ollomont IN','Ollomont OUT',
                            'FINISH'])

lifebase_stats_df

C:\Users\Karina\AppData\Local\Temp\ipykernel_5932\3803803905.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge['Duration_seconds'][df_merge['Duration_seconds']  <= 0] = np.nan

Sub-70
Sub-80
Sub-90
Sub-100
Sub-110
Sub-120
Sub-130
Sub-140
Sub-150
Over-150
nan
DNF

,Finish Category,Lifebase,Count_Finish_Category_Lifebase_seconds,Mean_Finish_Category_Lifebase_seconds,Median_Finish_Category_Lifebase_seconds,STD_Finish_CategoryLifebaset_seconds,Min_Finish_Category_Lifebase_seconds,Max_Finish_Category_Lifebase_seconds,running_total_mean_seconds,running_total_median_seconds,Stage
80,Sub-130,Valgrisenche IN,656.0,41120.0,40957.0,4050.0,30261.0,55736.0,41120.0,40957.0,Stage 1
136,Sub-80,Valgrisenche IN,30.0,27346.0,27087.0,1601.0,25360.0,32039.0,27346.0,27087.0,Stage 1
38,Sub-100,Valgrisenche IN,116.0,32529.0,32363.0,2588.0,25495.0,40300.0,32529.0,32363.0,Stage 1
94,Sub-140,Valgrisenche IN,451.0,43937.0,43884.0,4071.0,34456.0,58846.0,43937.0,43884.0,Stage 1
66,Sub-120,Valgrisenche IN,315.0,38295.0,38134.0,3379.0,30903.0,52726.0,38295.0,38134.0,Stage 1
...,...,...,...,...,...,...,...,...,...,...,...
32,Sub-100,FINISH,111.0,49311.0,48629.0,5643.0,30958.0,62121.0,345619.0,339594.0,Stage 7
130,Sub-80,FINISH,29.0,42915.0,41662.0,6542.0,34872.0,67163.0,272349.0,267028.0,Stage 7
88,Sub-140,FINISH,440.0,61172.0,60666.0,8348.0,41533.0,105421.0,484407.0,478794.0,Stage 7
4,DNF,FINISH,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stage 7
46,Sub-110,FINISH,242.0,48683.0,48858.0,5972.0,34285.0,82722.0,379705.0,374272.0,Stage 7

In [22]:
# # # Convert integer seconds to timedelta
lifebase_stats_df['Median_Finish_Category_Lifebase'] = pd.to_timedelta(lifebase_stats_df['Median_Finish_Category_Lifebase_seconds'], unit='s')


lifebase_stats_df[['Finish Category','Lifebase', 'Median_Finish_Category_Lifebase']][lifebase_stats_df['Finish Category'] == 'Sub-130']

   Finish Category           Lifebase Median_Finish_Category_Lifebase
80         Sub-130    Valgrisenche IN                 0 days 11:22:37
81         Sub-130   Valgrisenche OUT                 0 days 00:54:53
70         Sub-130           Cogne IN                 0 days 16:56:32
71         Sub-130          Cogne OUT                 0 days 02:13:20
72         Sub-130          Donnas IN                 0 days 12:03:49
73         Sub-130         Donnas OUT                 0 days 02:32:51
75         Sub-130       Gressoney IN                 0 days 22:30:52
76         Sub-130      Gressoney OUT                 0 days 03:05:24
82         Sub-130   Valtournenche IN                 0 days 11:34:13
83         Sub-130  Valtournenche OUT                 0 days 03:20:12
77         Sub-130        Ollomont IN                 0 days 18:43:47
78         Sub-130       Ollomont OUT                 0 days 02:54:50
74         Sub-130             FINISH                 0 days 16:02:38

In [23]:
checkpoints_stats_df = creating_time_stats(df = checkpoints_bib_df, 
                    column = 'Checkpoint', 
                    category_order = ['La Thuile', 'Valgrisenche IN', 'Valgrisenche OUT',
                                       'Eaux Rousse', 'Cogne IN', 'Cogne OUT', 'Donnas IN', 'Donnas OUT',
                                       'Rifugio della Barma', 'Niel La Gruba', 'Gressoney IN',
                                       'Gressoney OUT', 'Champoluc', 'Valtournenche IN',
                                       'Valtournenche OUT', 'Oyace', 'Ollomont IN', 'Ollomont OUT',
                                       'FINISH'])

checkpoints_stats_df

C:\Users\Karina\AppData\Local\Temp\ipykernel_5932\3803803905.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge['Duration_seconds'][df_merge['Duration_seconds']  <= 0] = np.nan

Sub-70
Sub-80
Sub-90
Sub-100
Sub-110
Sub-120
Sub-130
Sub-140
Sub-150
Over-150
nan
DNF

,Finish Category,Checkpoint,Count_Finish_Category_Checkpoint_seconds,Mean_Finish_Category_Checkpoint_seconds,Median_Finish_Category_Checkpoint_seconds,STD_Finish_CategoryCheckpointt_seconds,Min_Finish_Category_Checkpoint_seconds,Max_Finish_Category_Checkpoint_seconds,running_total_mean_seconds,running_total_median_seconds,Stage
109,Sub-130,La Thuile,662.0,12670.0,12351.0,1993.0,8913.0,21942.0,12670.0,12351.0,Stage 1
49,Sub-100,La Thuile,115.0,10286.0,10139.0,1161.0,8291.0,17390.0,10286.0,10139.0,Stage 1
69,Sub-110,La Thuile,244.0,11228.0,11033.0,1716.0,8614.0,19770.0,11228.0,11033.0,Stage 1
89,Sub-120,La Thuile,314.0,11975.0,11744.0,1765.0,9235.0,21590.0,11975.0,11744.0,Stage 1
29,Over-150,La Thuile,24.0,17714.0,16074.0,3550.0,12416.0,23751.0,17714.0,16074.0,Stage 1
...,...,...,...,...,...,...,...,...,...,...,...
135,Sub-140,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,Sub-150,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,Sub-70,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,Sub-80,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,Sub-90,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
all_aid_station_bib_stats_df = creating_time_stats(df = all_aid_station_bib_df, 
                    column = 'Aid Station', 
                    category_order = ['Baite Youlaz', 'La Thuile', 'Rifugio Deffeyes',
                                   'Planaval', 'Valgrisenche IN', 'Valgrisenche OUT', 'Chalet Epee',
                                   'Rhemes-Notre-Dame', 'Eaux Rousse', 'Rifugio Sella', 'Cogne IN',
                                   'Cogne OUT', 'Goilles', 'Rifugio Dondena', 'Chardonney', 'Pontboset',
                                   'Donnas IN', 'Donnas OUT', 'Perloz', 'Sassa', 'Rifugio Coda',
                                   'Rifugio della Barma', 'Lago Chiaro', 'Col della Vecchia',
                                   'Niel La Gruba', 'Loo', 'Gressoney IN', 'Gressoney OUT',
                                   'Rifugio Alpenzu', 'Champoluc', 'Rifugio Grand Tournalin',
                                   'Valtournenche IN', 'Valtournenche OUT', 'Rifugio Barmasse', 'Vareton',
                                   'Rifugio Magià', 'Rifugio Cuney', 'Bivacco R. Clermont', 'Oyace',
                                   'Bruson Arp', 'Ollomont IN', 'Ollomont OUT', 'Rifugio Champillon',
                                   'Ponteille Desot', 'Bosses', 'Rifugio Frassati', 'Pas Entre Deux Sauts',
                                   'Monte de la Saxe', 'FINISH'])

all_aid_station_bib_stats_df

C:\Users\Karina\AppData\Local\Temp\ipykernel_5932\3803803905.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge['Duration_seconds'][df_merge['Duration_seconds']  <= 0] = np.nan

Sub-70
Sub-80
Sub-90
Sub-100
Sub-110
Sub-120
Sub-130
Sub-140
Sub-150
Over-150
nan
DNF

,Finish Category,Aid Station,Count_Finish_Category_Aid Station_seconds,Mean_Finish_Category_Aid Station_seconds,Median_Finish_Category_Aid Station_seconds,STD_Finish_CategoryAid Stationt_seconds,Min_Finish_Category_Aid Station_seconds,Max_Finish_Category_Aid Station_seconds,running_total_mean_seconds,running_total_median_seconds,Stage
0,DNF,Baite Youlaz,1090.0,11267.0,10868.0,2981.0,2675.0,25515.0,11267.0,10868.0,Stage 1
500,Sub-90,Baite Youlaz,57.0,7385.0,7163.0,1071.0,6497.0,14255.0,7385.0,7163.0,Stage 1
100,Sub-100,Baite Youlaz,117.0,7889.0,7813.0,970.0,6377.0,14876.0,7889.0,7813.0,Stage 1
150,Sub-110,Baite Youlaz,242.0,8661.0,8420.0,1580.0,6594.0,16855.0,8661.0,8420.0,Stage 1
200,Sub-120,Baite Youlaz,311.0,9181.0,8981.0,1595.0,6925.0,17628.0,9181.0,8981.0,Stage 1
...,...,...,...,...,...,...,...,...,...,...,...
344,Sub-140,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,Sub-150,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
444,Sub-70,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,Sub-80,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
544,Sub-90,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Who ran too easy or hard at the start?

In [ ]:
# sub_TOR330_dem_bib_list = list(TOR330_dem['PK'][TOR330_dem['Finish Category'] == 'Sub-130'].unique())

# new_bib_list = []
# for bib in sub_TOR330_dem_bib_list:
#     df = lifebase_bib_df[
#                 ((lifebase_bib_df['Duration_hours']> 14) &
#                 (lifebase_bib_df['Lifebase'] == 'Valgrisenche IN') )
#     &
#                 (lifebase_bib_df['PK']== bib)
#                ]
    
#     new_bib_list.append(df)
# df= pd.concat(new_bib_list)
# pk_unique = list(df['PK'].unique())

# for pk in pk_unique:
#     print(lifebase_bib_df[['PK','Lifebase', 'Timestamp', 'Duration_hours']][(lifebase_bib_df['PK'] == pk)  ], '\n', '*'*40,  '\n',)
#     print(TOR330_dem[['PK', 'Finish Category', 'Duration_hours']][(TOR330_dem['PK'] == pk)  ], '\n','\n','\n','\n', '*'*40,  '\n',)

In [ ]:
# sub_TOR330_dem_bib_list = list(TOR330_dem['PK'][TOR330_dem['Finish Category'] == 'Sub-140'].unique())

# new_bib_list = []
# for bib in sub_TOR330_dem_bib_list:
#     df = lifebase_bib_df[
#                 ((lifebase_bib_df['Duration_hours']< 10) &
#                 (lifebase_bib_df['Lifebase'] == 'Valgrisenche IN') ) &
#                 (lifebase_bib_df['PK']== bib)]
#     new_bib_list.append(df)
    
# df= pd.concat(new_bib_list)

# pk_unique = list(df['PK'].unique())

# for pk in pk_unique:
#     print(lifebase_bib_df[['PK', 'Wave', 'Lifebase', 'Duration_hours']][(lifebase_bib_df['PK'] == pk)  ], '\n', '\n',)
#     print(TOR330_dem[['PK', 'Finish Category', 'Duration_hours']][(TOR330_dem['PK'] == pk)  ], '\n', '*'*40,  '\n',)

In [ ]:
# # reading in Raw Data
# races = ['TOR330']
# years = [ 
# #     '2021',
# #         '2022',
# #          '2023', 
#     '2024'
#         ]

# TORX_df = {}

# for race in races:
#     for year in years:
#         df = pd.read_excel(f'{race} Data/1. 100x100trail/{race}_{year}.xlsx',
#                                  dtype={'Start Date': 'string',
#                                         'Year': 'string'})
#         print(f'{race}_{year} {df.shape}')
#         # Store the DataFrame in the dictionary with a key like 'TOR330_2021'
#         TORX_df[f'{race}_{year}'] = df
#     print('*'*50)
    
# TORX_df_concat = pd.concat(TORX_df)
# TOR330 = TORX_df_concat[TORX_df_concat['Year'] == year]

In [ ]:
# sub_TOR330_dem_bib_list = list(TOR330_dem['PK'][TOR330_dem['Finish Category'] == 'Sub-90'].unique())

# new_bib_list = []
# for bib in sub_TOR330_dem_bib_list:
#     df = lifebase_bib_df[
#                 ((lifebase_bib_df['Duration_hours']> 8) &
#                 (lifebase_bib_df['Lifebase'] == 'Valgrisenche OUT') ) &
#                 (lifebase_bib_df['PK']== bib)]
#     new_bib_list.append(df)
    
# df= pd.concat(new_bib_list)

# pk_unique = list(df['PK'].unique())

# for pk in pk_unique:
#     print(lifebase_bib_df[['PK', 'Wave', 'Lifebase', 'Duration_hours']][(lifebase_bib_df['PK'] == pk)  ], '\n', '\n',)
#     print(TOR330_dem[['PK', 'Finish Category', 'Duration_hours']][(TOR330_dem['PK'] == pk)  ], '\n', '*'*40,  '\n',)

In [12]:
# no_banking_df = lifebase_bib_df[(lifebase_bib_df['Status1'].str.contains( 'Courmayeur')) &
#                 (lifebase_bib_df['Lifebase'] != 'START') &
#                 (lifebase_bib_df['Banking Time_seconds'] <0)]

# no_banking_df['Banking Time_seconds'] = no_banking_df['Banking Time_seconds'].astype(int)
# # Apply function to the column
# no_banking_df['Banking Time'] =pd.to_timedelta(no_banking_df['Banking Time_seconds'], unit='s').astype(str)
# no_banking_df['Running Total Duration'] =pd.to_timedelta(no_banking_df['Running Total Duration_seconds'], unit='s').astype(str)

# for unique_name in no_banking_df['Name']:
#     print(no_banking_df[['Name','Year', 'Race', 'Lifebase','Running Total Duration', 'Banking Time']][no_banking_df['Name'] == unique_name])
#     print('*'*40)

NameError: name 'no_banking_df' is not defined