In [1]:
import requests
import json
import html
import pandas as pd
import time
import numpy as np
import matplotlib.pyplot as plt
import unicodedata
import re

C:\Users\Karina\miniconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (2.2.2) or chardet (3.0.4)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn(

In [2]:
# Function to remove special characters
def normalize_name(name):
    # Normalize to remove accents and special characters
    name = unicodedata.normalize('NFD', name)
    # Encode to ASCII and ignore errors, then decode back to string
    name = name.encode('ascii', 'ignore').decode('utf-8')
    return name

In [3]:

# # URL of the JSON file
# url = "https://itra.run/Races/RaceResults/TOR330.Tor.des.G%C3%A9ants%C2%AE/2023/80226"

# # Send a GET request to fetch the JSON data
# response = requests.get(url)
# response

In [4]:
years = [ '2024', '2023', 
         '2022', 
         '2022_HOTEL_ITALIA',  # bad weather at the end 
         '2022_RIFUGIO_FRASSATI',
         '2022_BOSSES',
         '2021', 
         '2019',
#          '2020', # cancelled due to covid
         '2018', '2017', '2016', 
         '2015', 
         '2015_BOSSES',
        '2015_GRESSONEY',
        '2015_OLLOMONT',
        '2015_OYACE',
        '2015_RIFUGIO_CREST',
        '2015_RIGUGIO_CUNEY',
        '2015_Saint_Jacques',
        '2015_VALTOURENCHE',
       
         '2014', '2013', '2012', '2012_303','2011', '2010']

races = [#'TOR130',
    'TOR330', 
#          'TOR450'
        ]

#### Loading ITRA

In [5]:

TORX_itra_df = {}
# races = ['TOR450']

for race in races:
    for year in years:
        try:

            file = f'{race} Data/3. ITRA/TXT/{race}_{year}.txt'
            df = pd.read_csv(file, delimiter='\t', 
                         dtype={'Time': 'string'})    

            # renaming columns so it is easier later to compare
            df = df.rename(columns={"Runner": "Name",
                                    "Gender": "Sex",
                                    "Nationality": "ITRA_Nationality",
                                   })

            # change the name to a title case
            df['Name'] = df['Name'].str.title()
            df['Name'] = df['Name'].apply(normalize_name)
            

            # Convert 'Time' to timedelta format
            df['Performance'] = pd.to_timedelta(df['Time'], errors='coerce')
            # Calculate total seconds and create 'Performance_Seconds' column
            df['Performance_Seconds'] = df['Performance'].dt.total_seconds()

            if year == '2022_HOTEL_ITALIA':
            # Create the 'Status' column
                df['Status'] =  'Finished at Hotel Italia'
                df['Year'] = '2022'    
            elif year == '2022_RIFUGIO_FRASSATI':
                df['Status'] = 'Finished at Rifugio Frassati'
                df['Year'] = '2022'
            elif year == '2022_BOSSES':
                df['Status'] =  'Finished at Bosses'
                df['Year'] = '2022'                
            elif year == '2015_GRESSONEY':
                df['Status'] = 'Finished at Gressoney'
                df['Year'] = '2015'
            elif year == '2015_BOSSES':
                df['Status'] =  'Finished at Bosses'
                df['Year'] = '2015'
            elif year == '2015_OLLOMONT':
                df['Status'] =  'Finished at Ollomont'
                df['Year'] = '2015'
            elif year == '2015_OYACE':
                df['Status'] =  'Finished at Oyace'
                df['Year'] = '2015'
            elif year == '2015_RIFUGIO_CREST':
                df['Status'] =  'Finished at Rifugio Crest'
                df['Year'] = '2015'
            elif year == '2015_OYACE':
                df['Status'] =  'Finished at Oyace'
                df['Year'] = '2015'
            elif year == '2015_RIGUGIO_CUNEY':
                df['Status'] =  'Finished at Rifugio Cuney'
                df['Year'] = '2015'
            elif year == '2015_Saint_Jacques':
                df['Status'] =  'Finished at Saint Jacques'
                df['Year'] = '2015'
            elif year == '2015_VALTOURENCHE':
                df['Status'] =  'Finished at VALTOURENCHE'
                df['Year'] = '2015'
            elif year == '2012_303':
                df['Status'] =  'Finished at 303'
                df['Year'] = '2012'          
        
        
            else:
                df['Status'] = np.where(df['Performance'].isna(), 'DNF', 'Finished')
                df['Year'] = f'{year}'

            df['Race'] = f'{race}'

    #             # Drop the intermediate columns if they're no longer needed
            df = df.drop(columns=['Time', '#'])

            df['Name'] = df['Name'].str.strip()
            df['Name'] = df['Name'].str.replace(',', '')
            df['Name'] = df['Name'].str.replace('\'', '')
            df['Name'] = df['Name'].str.replace('-', '')
            df['Name'] = df['Name'].str.replace(r"\s+", " ")

    #             print(race, year, '\n', df.head())

            # Store the DataFrame in the dictionary with a key like 'TOR330_2021'
            TORX_itra_df[f'{race}_{year}'] = df
            print('* ',f'{race}_{year} {df.shape}', '\n')
        except:
            
            if file == 'TOR330 Data/3. ITRA/TXT/TOR330_2022_HOTEL_ITALIA.txt':
                pass
            elif file == 'TOR450 Data/3. ITRA/TXT/TOR450_2022_RIFUGIO_FRASSATI.txt':
                pass
            elif file == 'TOR450 Data/3. ITRA/TXT/TOR330_2022_BOSSES.txt':
                pass
            
            else:
                print(f'issues with {race}_{year}')
                print(f'{file}')
                print('\n')

C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")

*  TOR330_2024 (1085, 9)

*  TOR330_2023 (1093, 9)

*  TOR330_2022 (408, 9)

*  TOR330_2022_RIFUGIO_FRASSATI (101, 9)

*  TOR330_2022_BOSSES (81, 9)

*  TOR330_2021 (712, 9)

C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")

*  TOR330_2019 (941, 9)

*  TOR330_2018 (879, 9)

*  TOR330_2017 (461, 9)

*  TOR330_2016 (445, 9)

*  TOR330_2015 (6, 9)

C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")

*  TOR330_2015_BOSSES (4, 10)

*  TOR330_2015_GRESSONEY (223, 9)

*  TOR330_2015_OLLOMONT (24, 9)

*  TOR330_2015_OYACE (16, 9)

*  TOR330_2015_RIFUGIO_CREST (42, 10)

*  TOR330_2015_RIGUGIO_CUNEY (18, 9)

*  TOR330_2015_Saint_Jacques (65, 9)

*  TOR330_2015_VALTOURENCHE (75, 9)

C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")

*  TOR330_2014 (443, 9)

*  TOR330_2013 (383, 9)

*  TOR330_2012 (73, 9)

*  TOR330_2012_303 (319, 9)

*  TOR330_2011 (300, 9)

*  TOR330_2010 (179, 9)

C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\1351629977.py:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")

In [6]:
for race in races:
    for year in years:
        try:
            tor_year = TORX_itra_df[f'{race}_{year}']
            # Count the occurrences of each status
            status_counts = tor_year['Status'].value_counts()
            print(race, year, '\n', status_counts, '\n', '*'*40)
        except:
            pass

TOR330 2024
 DNF         552
Finished    533
Name: Status, dtype: int64
 ****************************************
TOR330 2023
 Finished    621
DNF         472
Name: Status, dtype: int64
 ****************************************
TOR330 2022
 Finished    408
Name: Status, dtype: int64
 ****************************************
TOR330 2022_RIFUGIO_FRASSATI
 Finished at Rifugio Frassati    101
Name: Status, dtype: int64
 ****************************************
TOR330 2022_BOSSES
 Finished at Bosses    81
Name: Status, dtype: int64
 ****************************************
TOR330 2021
 Finished    431
DNF         281
Name: Status, dtype: int64
 ****************************************
TOR330 2019
 Finished    563
DNF         378
Name: Status, dtype: int64
 ****************************************
TOR330 2018
 Finished    534
DNF         345
Name: Status, dtype: int64
 ****************************************
TOR330 2017
 Finished    461
Name: Status, dtype: int64
 ****************************************
TOR330 2016
 Finished    445
Name: Status, dtype: int64
 ****************************************
TOR330 2015
 Finished    6
Name: Status, dtype: int64
 ****************************************
TOR330 2015_BOSSES
 Finished at Bosses    4
Name: Status, dtype: int64
 ****************************************
TOR330 2015_GRESSONEY
 Finished at Gressoney    223
Name: Status, dtype: int64
 ****************************************
TOR330 2015_OLLOMONT
 Finished at Ollomont    24
Name: Status, dtype: int64
 ****************************************
TOR330 2015_OYACE
 Finished at Oyace    16
Name: Status, dtype: int64
 ****************************************
TOR330 2015_RIFUGIO_CREST
 Finished at Rifugio Crest    42
Name: Status, dtype: int64
 ****************************************
TOR330 2015_RIGUGIO_CUNEY
 Finished at Rifugio Cuney    18
Name: Status, dtype: int64
 ****************************************
TOR330 2015_Saint_Jacques
 Finished at Saint Jacques    65
Name: Status, dtype: int64
 ****************************************
TOR330 2015_VALTOURENCHE
 Finished at VALTOURENCHE    75
Name: Status, dtype: int64
 ****************************************
TOR330 2014
 Finished    443
Name: Status, dtype: int64
 ****************************************
TOR330 2013
 Finished    383
Name: Status, dtype: int64
 ****************************************
TOR330 2012
 Finished    73
Name: Status, dtype: int64
 ****************************************
TOR330 2012_303
 Finished at 303    319
Name: Status, dtype: int64
 ****************************************
TOR330 2011
 Finished    300
Name: Status, dtype: int64
 ****************************************
TOR330 2010
 Finished    179
Name: Status, dtype: int64
 ****************************************

In [7]:
TORX_itra_df

{'TOR330_2024':                     Name Age Sex ITRA_Nationality     Performance  \
 0       D Haene Francois  39   M              FRA 2 days 21:08:32
 1      Marmissolle Benat  43   M              FRA 3 days 01:10:18
 2         Perrier Martin  34   M              FRA 3 days 03:35:59
 3          Macchi Andrea  38   M              ITA 3 days 04:43:09
 4            Hall Damian  49   M              GBR 3 days 04:49:20
 ...                  ...  ..  ..              ...             ...
 1080        Zimei Andrea  44   M              ITA             NaT
 1081  Zinfolino Federica  47   F              ITA             NaT
 1082       Zoratti Mauro  36   M              ITA             NaT
 1083       Zou Hongjiang  43   M              CHN             NaT
 1084                      56   M              JPN             NaT

       Performance_Seconds    Status  Year    Race
 0                248912.0  Finished  2024  TOR330
 1                263418.0  Finished  2024  TOR330
 2                272159.0  Finished  2024  TOR330
 3                276189.0  Finished  2024  TOR330
 4                276560.0  Finished  2024  TOR330
 ...                   ...       ...   ...     ...
 1080                  NaN       DNF  2024  TOR330
 1081                  NaN       DNF  2024  TOR330
 1082                  NaN       DNF  2024  TOR330
 1083                  NaN       DNF  2024  TOR330
 1084                  NaN       DNF  2024  TOR330

 [1085 rows x 9 columns],
 'TOR330_2023':                   Name Age Sex ITRA_Nationality     Performance  \
 0         Colle Franco  45   M              ITA 2 days 18:39:16
 1       Olivier Romain  38   M              FRA 2 days 21:49:38
 2       Reynolds Galen  39   M              CAN 2 days 23:22:30
 3          Hall Damian  48   M              GBR 3 days 00:04:07
 4     Galeati Gianluca  40   M              ITA 3 days 00:16:06
 ...                ...  ..  ..              ...             ...
 1088    Zenato Michele  58   M              ITA             NaT
 1089         Zhao Long  44   M              CHN             NaT
 1090    Zheng Xiao Hui  52   M              CAN             NaT
 1091     Ziemba Damian  45   M              POL             NaT
 1092     Zou Hongjiang  42   M              CHN             NaT

       Performance_Seconds    Status  Year    Race
 0                239956.0  Finished  2023  TOR330
 1                251378.0  Finished  2023  TOR330
 2                256950.0  Finished  2023  TOR330
 3                259447.0  Finished  2023  TOR330
 4                260166.0  Finished  2023  TOR330
 ...                   ...       ...   ...     ...
 1088                  NaN       DNF  2023  TOR330
 1089                  NaN       DNF  2023  TOR330
 1090                  NaN       DNF  2023  TOR330
 1091                  NaN       DNF  2023  TOR330
 1092                  NaN       DNF  2023  TOR330

 [1093 rows x 9 columns],
 'TOR330_2022':                          Name Age Sex ITRA_Nationality     Performance  \
 0                 Russi Jonas  37   M              SUI 2 days 22:31:36
 1              Corsini Simone  30   M              ITA 3 days 03:27:33
 2               Macchi Andrea  36   M              ITA 3 days 04:43:50
 3             Mattiato Andrea  44   M              ITA 3 days 06:22:28
 4              Sabrina Verjee  41   F              GBR 3 days 08:19:38
 ..                        ...  ..  ..              ...             ...
 403            Bentham Darren  54   M              GBR 5 days 22:58:14
 404            Longhi Giorgio  53   M              ITA 5 days 22:58:18
 405             Costa Alberto  38   M              ITA 6 days 00:21:06
 406  Colletto Davide Colletto  36   M              ITA 6 days 00:21:18
 407  Amar Delapierre Jocelyne  59   F              FRA 6 days 00:33:43

      Performance_Seconds    Status  Year    Race
 0               253896.0  Finished  2022  TOR330
 1               271653.0  Finished  2022  TOR330
 2               276230.0  Finished  2022  TOR330
 3               282148.0  Finished  2022  TOR330
 4               289178.0  Finished  2022  TOR330
 ..                   ...       ...   ...     ...
 403             514694.0  Finished  2022  TOR330
 404             514698.0  Finished  2022  TOR330
 405             519666.0  Finished  2022  TOR330
 406             519678.0  Finished  2022  TOR330
 407             520423.0  Finished  2022  TOR330

 [408 rows x 9 columns],
 'TOR330_2022_RIFUGIO_FRASSATI':                             Name Age Sex ITRA_Nationality     Performance  \
 0                Roveri Giovanni  53   M              ITA 5 days 07:59:29
 1                    Rossi Carlo  50   M              ITA 5 days 08:17:39
 2              Severino Giovanni  47   M              ITA 5 days 10:01:00
 3             Lloyd Hughes Torin  21   M              GBR 5 days 11:44:40
 4                 Borne Aurelien  38   M              FRA 5 days 12:04:17
 ..                           ...  ..  ..              ...             ...
 96   Rioboo Escalante Jon Mirena  56   M              ESP 5 days 20:26:55
 97          Riera Campillo Pablo  49   M              ESP 5 days 20:26:59
 98                  Werneck Fred  43   M              BRA 5 days 20:27:50
 99                  Lelu Olivier  52   M              FRA 5 days 20:49:44
 100                    Huang Ken  51   F              USA 5 days 22:26:49

      Performance_Seconds                        Status  Year    Race
 0               460769.0  Finished at Rifugio Frassati  2022  TOR330
 1               461859.0  Finished at Rifugio Frassati  2022  TOR330
 2               468060.0  Finished at Rifugio Frassati  2022  TOR330
 3               474280.0  Finished at Rifugio Frassati  2022  TOR330
 4               475457.0  Finished at Rifugio Frassati  2022  TOR330
 ..                   ...                           ...   ...     ...
 96              505615.0  Finished at Rifugio Frassati  2022  TOR330
 97              505619.0  Finished at Rifugio Frassati  2022  TOR330
 98              505670.0  Finished at Rifugio Frassati  2022  TOR330
 99              506984.0  Finished at Rifugio Frassati  2022  TOR330
 100             512809.0  Finished at Rifugio Frassati  2022  TOR330

 [101 rows x 9 columns],
 'TOR330_2022_BOSSES':                  Name Age Sex ITRA_Nationality     Performance  \
 0     Broggi Vittorio  61   M              ITA 5 days 10:42:26
 1    Balossi Giordano  53   M              ITA 5 days 11:17:16
 2     Renard Delphine  40   F              BEL 5 days 11:51:02
 3   Tsujimoto Arihito  52   M              JPN 5 days 12:42:55
 4      Butler Rebecca  51   F              AUS 5 days 12:46:27
 ..                ...  ..  ..              ...             ...
 76   Bertrand Ludovic  56   M              FRA 5 days 20:17:15
 77   Diemoz Ferruccio  52   M              ITA 5 days 20:17:24
 78         Kurita Eri  50   F              JPN 5 days 20:18:03
 79       Isidori Luca  56   M              ITA 5 days 20:18:22
 80      Ghedi Osvaldo  55   M              ITA 5 days 20:18:40

     Performance_Seconds              Status  Year    Race
 0              470546.0  Finished at Bosses  2022  TOR330
 1              472636.0  Finished at Bosses  2022  TOR330
 2              474662.0  Finished at Bosses  2022  TOR330
 3              477775.0  Finished at Bosses  2022  TOR330
 4              477987.0  Finished at Bosses  2022  TOR330
 ..                  ...                 ...   ...     ...
 76             505035.0  Finished at Bosses  2022  TOR330
 77             505044.0  Finished at Bosses  2022  TOR330
 78             505083.0  Finished at Bosses  2022  TOR330
 79             505102.0  Finished at Bosses  2022  TOR330
 80             505120.0  Finished at Bosses  2022  TOR330

 [81 rows x 9 columns],
 'TOR330_2021':                                Name Age Sex ITRA_Nationality     Performance  \
 0                      Colle Franco  43   M              ITA 2 days 18:43:57
 1                       Jonas Russi  36   M              SUI 2 days 21:03:00
 2                    Restorp Petter  44   M              SWE 3 days 04:36:00
 3                     Picinali Luca  48   M              ITA 3 days 09:31:00
 4                    Corsini Simone  29   M              ITA 3 days 10:45:52
 ..                              ...  ..  ..              ...             ...
 707  Zanderighi Luca Giovanni Maria  63   M              ITA             NaT
 708                 Zanon Francesco  26   M              ITA             NaT
 709               Zapata Munoz Juan  48   M              ESP             NaT
 710   Zavelani Rossi Maria Beatrice  56   F              ITA             NaT
 711                  Zenato Michele  56   M              ITA             NaT

      Performance_Seconds    Status  Year    Race
 0               240237.0  Finished  2021  TOR330
 1               248580.0  Finished  2021  TOR330
 2               275760.0  Finished  2021  TOR330
 3               293460.0  Finished  2021  TOR330
 4               297952.0  Finished  2021  TOR330
 ..                   ...       ...   ...     ...
 707                  NaN       DNF  2021  TOR330
 708                  NaN       DNF  2021  TOR330
 709                  NaN       DNF  2021  TOR330
 710                  NaN       DNF  2021  TOR330
 711                  NaN       DNF  2021  TOR330

 [712 rows x 9 columns],
 'TOR330_2019':                    Name Age Sex ITRA_Nationality     Performance  \
 0    Bosatelli Oliviero  50   M              ITA 3 days 00:37:13
 1        Reynolds Galen  35   M              CAN 3 days 05:06:12
 2     Lantermino Danilo  38   M              ITA 3 days 07:09:46
 3           Erwee Tiaan  32   M              RSA 3 days 08:18:24
 4            Lukas Jens  53   M              GER 3 days 13:04:04
 ..                  ...  ..  ..              ...             ...
 936         Zhang Yuren  48   M              CHN             NaT
 937        Zhao Yingkai  39   M              CHN             NaT
 938        Zheng Junyue  33   F              CHN             NaT
 939   Zimmermann Denise  44   F              SUI             NaT
 940       Zoppi Filippo  48   M              ITA             NaT

      Performance_Seconds    Status  Year    Race
 0               261433.0  Finished  2019  TOR330
 1               277572.0  Finished  2019  TOR330
 2               284986.0  Finished  2019  TOR330
 3               289104.0  Finished  2019  TOR330
 4               306244.0  Finished  2019  TOR330
 ..                   ...       ...   ...     ...
 936                  NaN       DNF  2019  TOR330
 937                  NaN       DNF  2019  TOR330
 938                  NaN       DNF  2019  TOR330
 939                  NaN       DNF  2019  TOR330
 940                  NaN       DNF  2019  TOR330

 [941 rows x 9 columns],
 'TOR330_2018':                    Name Age Sex ITRA_Nationality     Performance  \
 0          Colle Franco  40   M              ITA 3 days 02:03:00
 1        Reynolds Galen  34   M              CAN 3 days 02:40:36
 2          Kienzl Peter  43   M              ITA 3 days 05:31:11
 3    Bosatelli Oliviero  49   M              ITA 3 days 08:49:26
 4         Toriumi Kouta  33   M              JPN 3 days 08:58:35
 ..                  ...  ..  ..              ...             ...
 874           Zdon Bill  33   M              USA             NaT
 875      Zennaro Davide  57   M              ITA             NaT
 876        Zimei Andrea  38   M              ITA             NaT
 877   Zimmermann Denise  43   F              SUI             NaT
 878        Zugna Davide  42   M              ITA             NaT

      Performance_Seconds    Status  Year    Race
 0               266580.0  Finished  2018  TOR330
 1               268836.0  Finished  2018  TOR330
 2               279071.0  Finished  2018  TOR330
 3               290966.0  Finished  2018  TOR330
 4               291515.0  Finished  2018  TOR330
 ..                   ...       ...   ...     ...
 874                  NaN       DNF  2018  TOR330
 875                  NaN       DNF  2018  TOR330
 876                  NaN       DNF  2018  TOR330
 877                  NaN       DNF  2018  TOR330
 878                  NaN       DNF  2018  TOR330

 [879 rows x 9 columns],
 'TOR330_2017':                       Name Age Sex ITRA_Nationality     Performance  \
 0    Dominguez Ledo Javier  43   M              ESP 2 days 19:52:15
 1       Bosatelli Oliviero  48   M              ITA 2 days 21:16:19
 2            Macchi Andrea  31   M              ITA 3 days 02:51:14
 3                Sa Carlos  44   M              POR 3 days 08:20:34
 4            Aleson Imanol  45   M              ESP 3 days 09:17:37
 ..                     ...  ..  ..              ...             ...
 456             Juang Than  39   M              THA 6 days 05:45:13
 457   Rumyantseva Evgeniya  33   F              RUS 6 days 05:45:50
 458       Yoshimoto Makoto  53   M              JPN 6 days 05:51:42
 459           Shi Jianxiao  33   M              CHN 6 days 06:39:42
 460           Ng Seow Kong  56   M              MAS 6 days 08:40:29

      Performance_Seconds    Status  Year    Race
 0               244335.0  Finished  2017  TOR330
 1               249379.0  Finished  2017  TOR330
 2               269474.0  Finished  2017  TOR330
 3               289234.0  Finished  2017  TOR330
 4               292657.0  Finished  2017  TOR330
 ..                   ...       ...   ...     ...
 456             539113.0  Finished  2017  TOR330
 457             539150.0  Finished  2017  TOR330
 458             539502.0  Finished  2017  TOR330
 459             542382.0  Finished  2017  TOR330
 460             549629.0  Finished  2017  TOR330

 [461 rows x 9 columns],
 'TOR330_2016':                      Name Age Sex ITRA_Nationality     Performance  \
 0      Bosatelli Oliviero  47   M              ITA 3 days 03:10:22
 1       Perez Lopez Oscar  43   M              ESP 3 days 09:14:50
 2       Criado Toca Pablo  40   M              ESP 3 days 11:40:10
 3        Ressencourt Eric  41   M              FRA 3 days 12:06:32
 4              Lukas Jens  50   M              GER 3 days 13:47:50
 ..                    ...  ..  ..              ...             ...
 440        Leveque Claude  37   M              ITA 6 days 05:40:09
 441      Yoshimoto Makoto  52   M              JPN 6 days 05:41:31
 442        Bourva Laurent  56   M              FRA 6 days 05:44:03
 443        Manoni Giorgio  45   M              ITA 6 days 05:55:38
 444  Bustamante Velez Ana  48   F              ESP 6 days 05:55:39

      Performance_Seconds    Status  Year    Race
 0               270622.0  Finished  2016  TOR330
 1               292490.0  Finished  2016  TOR330
 2               301210.0  Finished  2016  TOR330
 3               302792.0  Finished  2016  TOR330
 4               308870.0  Finished  2016  TOR330
 ..                   ...       ...   ...     ...
 440             538809.0  Finished  2016  TOR330
 441             538891.0  Finished  2016  TOR330
 442             539043.0  Finished  2016  TOR330
 443             539738.0  Finished  2016  TOR330
 444             539739.0  Finished  2016  TOR330

 [445 rows x 9 columns],
 'TOR330_2015':                   Name    Race Age   Sex  ITRA_Nationality     Performance  \
 0       Bohard Patrick  TOR330   M   FRA               NaN 3 days 08:20:35
 1     Galeati Gianluca  TOR330   M   ITA               NaN 3 days 08:44:34
 2   Le Saux Christophe  TOR330   M   FRA               NaN 3 days 09:19:25
 3  Mathieu Jean Claude  TOR330   M   FRA               NaN 3 days 10:40:23
 4         Ono Masahiro  TOR330   M   JPN               NaN 3 days 11:39:11
 5    Criado Toca Pablo  TOR330   M   ESP               NaN 3 days 15:15:14

    Performance_Seconds    Status  Year
 0             289235.0  Finished  2015
 1             290674.0  Finished  2015
 2             292765.0  Finished  2015
 3             297623.0  Finished  2015
 4             301151.0  Finished  2015
 5             314114.0  Finished  2015  ,
 'TOR330_2015_BOSSES':                     Name Race    Age   Sex  ITRA_Nationality     Performance  \
 0      Perez Lopez Oscar     M   ESP   NaN               NaN 3 days 09:13:42
 1        Mochizuki Shogo    38     M   JPN               NaN 3 days 08:43:22
 2           Kienzl Peter    40     M   ITA               NaN 3 days 08:59:29
 3  Cernuda Aldecoa Julio    35     M   ESP               NaN 3 days 10:02:05

    Performance_Seconds              Status  Year    Race
 0             292422.0  Finished at Bosses  2015  TOR330
 1             290602.0  Finished at Bosses  2015  TOR330
 2             291569.0  Finished at Bosses  2015  TOR330
 3             295325.0  Finished at Bosses  2015  TOR330  ,
 'TOR330_2015_GRESSONEY':                     Name    Race Age   Sex  ITRA_Nationality     Performance  \
 0           Zanella Rudj  TOR330   M   ITA               NaN 2 days 23:51:00
 1       Griessbach Denis  TOR330   M   GER               NaN 3 days 01:16:00
 2        Guazzo Raffaele  TOR330   M   ITA               NaN 3 days 01:22:00
 3            Marta Oskar  TOR330   M   ESP               NaN 3 days 01:55:00
 4           Willis Sarah  TOR330   F   USA               NaN 3 days 02:15:00
 ..                   ...     ...  ..   ...               ...             ...
 218          Bossen Erik  TOR330   M   DEN               NaN 3 days 15:58:03
 219  Efthimiadis Giorgos  TOR330   M   GRE               NaN 3 days 16:00:09
 220     Painigra Jacques  TOR330   M   FRA               NaN 3 days 16:00:20
 221         Celal Devrim  TOR330   M   CYP               NaN 3 days 16:14:02
 222     Vicquery Laurent  TOR330   M   ITA               NaN 3 days 16:28:23

      Performance_Seconds                 Status  Year
 0               258660.0  Finished at Gressoney  2015
 1               263760.0  Finished at Gressoney  2015
 2               264120.0  Finished at Gressoney  2015
 3               266100.0  Finished at Gressoney  2015
 4               267300.0  Finished at Gressoney  2015
 ..                   ...                    ...   ...
 218             316683.0  Finished at Gressoney  2015
 219             316809.0  Finished at Gressoney  2015
 220             316820.0  Finished at Gressoney  2015
 221             317642.0  Finished at Gressoney  2015
 222             318503.0  Finished at Gressoney  2015

 [223 rows x 9 columns],
 'TOR330_2015_OLLOMONT':                    Name  Race Age Sex ITRA_Nationality     Performance  \
 0     Zimmermann Denise        40   F              SUI 3 days 07:12:35
 1      Verdier Philippe        53   M              FRA 3 days 08:01:33
 2   Annovazzi Giancarlo        50   M              ITA 3 days 08:08:06
 3          Borzani Lisa        36   F              ITA 3 days 08:16:53
 4          Guerini Luca        49   M              ITA 3 days 08:27:25
 5         Aleson Imanol        43   M              ESP 3 days 08:33:54
 6           Iino Wataru        36   M              JPN 3 days 09:26:03
 7         Macchi Andrea        29   M              ITA 3 days 09:28:11
 8        Stevenin Mauro        51   M              ITA 3 days 10:34:51
 9          Ernst Thomas        51   M              SUI 3 days 10:38:34
 10     Sakata Keiichiro        35   M              JPN 3 days 11:14:34
 11            Papi Luca        35   M              ITA 3 days 11:17:20
 12     Valsesia Massimo        54   M              ITA 3 days 11:22:13
 13        Cavallo Fabio        31   M              ITA 3 days 11:25:17
 14       Martin Ludovic        38   M              FRA 3 days 12:29:17
 15         Lauret Denis        42   M              FRA 3 days 12:37:57
 16       Jeanney Gaetan        25   M              FRA 3 days 12:54:33
 17       Pfend Stephane        43   M              FRA 3 days 13:12:12
 18        Plavan Marina        54   F              ITA 3 days 13:55:00
 19           Keith Eoin        47   M              IRL 3 days 14:23:28
 20       Nancoz Michael        27   M              SUI 3 days 14:28:20

In [8]:
# Append using pd.concat
TORX_itra_df = pd.concat(TORX_itra_df)
TORX_itra_df = TORX_itra_df.reset_index(drop = True)
TORX_itra_df.isna().sum()

Name                      0
Age                     206
Sex                      14
ITRA_Nationality        659
Performance            2028
Performance_Seconds    2028
Status                    0
Year                      0
Race                      0
Race                   8372
Race Age               8170
Race Score             8334
dtype: int64

In [9]:
years_list = TORX_itra_df['Year'].unique()
race_list = TORX_itra_df['Race'].unique()

for race in races:
    for year in years_list:
        year_df = TORX_itra_df[(TORX_itra_df['Year'] == year) &
                              (TORX_itra_df['Race'] == race)]
        status_df = year_df['Status'].value_counts()
        
        if race == 'TOR450' and year in [ 
            #'2020', # cancelled due to covid
         '2018', '2017', '2016', 
         '2015', 
         '2014', '2013', '2012', '2011', '2010']:
            pass
        else:
            print(race, year,'\n',status_df, '\n', '*'*40)

TOR330 2024
 DNF         552
Finished    533
Name: Status, dtype: int64
 ****************************************
TOR330 2023
 Finished    621
DNF         472
Name: Status, dtype: int64
 ****************************************
TOR330 2022
 Finished                        408
Finished at Rifugio Frassati    101
Finished at Bosses               81
Name: Status, dtype: int64
 ****************************************
TOR330 2021
 Finished    431
DNF         281
Name: Status, dtype: int64
 ****************************************
TOR330 2019
 Finished    563
DNF         378
Name: Status, dtype: int64
 ****************************************
TOR330 2018
 Finished    534
DNF         345
Name: Status, dtype: int64
 ****************************************
TOR330 2017
 Finished    461
Name: Status, dtype: int64
 ****************************************
TOR330 2016
 Finished    445
Name: Status, dtype: int64
 ****************************************
TOR330 2015
 Finished at Gressoney        223
Finished at VALTOURENCHE      75
Finished at Saint Jacques     65
Finished at Rifugio Crest     42
Finished at Ollomont          24
Finished at Rifugio Cuney     18
Finished at Oyace             16
Finished                       6
Finished at Bosses             4
Name: Status, dtype: int64
 ****************************************
TOR330 2014
 Finished    443
Name: Status, dtype: int64
 ****************************************
TOR330 2013
 Finished    383
Name: Status, dtype: int64
 ****************************************
TOR330 2012
 Finished at 303    319
Finished            73
Name: Status, dtype: int64
 ****************************************
TOR330 2011
 Finished    300
Name: Status, dtype: int64
 ****************************************
TOR330 2010
 Finished    179
Name: Status, dtype: int64
 ****************************************

## EDA of ITRA

In [10]:
TORX_itra_df[TORX_itra_df['Sex'].isna()]

,Name,Age,Sex,ITRA_Nationality,Performance,Performance_Seconds,Status,Year,Race,Race,Race Age,Race Score
643,Coluccio Pasquale,60,NaN,ITA,NaT,NaN,DNF,2024,TOR330,NaN,NaN,NaN
1223,Bryant Shane,45,NaN,USA,4 days 23:30:03,430203.0,Finished,2023,TOR330,NaN,NaN,NaN
1608,DAngelo Deva,33,NaN,ITA,6 days 01:56:32,525392.0,Finished,2023,TOR330,NaN,NaN,NaN
1760,Cailleau Marie Aline,56,NaN,FRA,NaT,NaN,DNF,2023,TOR330,NaN,NaN,NaN
2307,Carlier Julien,43,NaN,FRA,4 days 20:36:16,419776.0,Finished,2022,TOR330,NaN,NaN,NaN
2419,Barrot Loic,41,NaN,FRA,5 days 06:22:53,454973.0,Finished,2022,TOR330,NaN,NaN,NaN
2698,Coluccio Pasquale,58,NaN,ITA,5 days 13:42:05,481325.0,Finished at Bosses,2022,TOR330,NaN,NaN,NaN
3180,Polotti Diego,49,NaN,ITA,6 days 05:02:17,536537.0,Finished,2021,TOR330,NaN,NaN,NaN
3259,Coluccio Pasquale,57,NaN,ITA,NaT,NaN,DNF,2021,TOR330,NaN,NaN,NaN
4831,Martignoni Alessandro,40,NaN,ITA,6 days 00:29:36,520176.0,Finished,2018,TOR330,NaN,NaN,NaN
5023,Coluccio Pasquale,54,NaN,ITA,NaT,NaN,DNF,2018,TOR330,NaN,NaN,NaN
5638,Oktem Ozgur,41,NaN,TUR,6 days 01:23:58,523438.0,Finished,2017,TOR330,NaN,NaN,NaN
6212,Perez Lopez Oscar,ESP,NaN,NaN,3 days 09:13:42,292422.0,Finished at Bosses,2015,TOR330,M,NaN,NaN
7491,Coluccio Pasquale,49,NaN,ITA,6 days 04:24:39,534279.0,Finished,2013,TOR330,NaN,NaN,NaN

### Status 1 - Race cut short

In [11]:
TORX_itra_df['Status1'] = TORX_itra_df['Status'].copy()  
TORX_itra_df.loc[(TORX_itra_df['Status'].str.contains('Finished ') ) &
                 
                 ((TORX_itra_df['Year'] == '2015') |
                  (TORX_itra_df['Year'] == '2022') | 
                  (TORX_itra_df['Year'] == '2012')), 'Status1'] = 'Race Cut Short'

In [12]:
TORX_itra_df.groupby(['Status1', 'Year'])['Status1', 'Year'].count()

C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\228128164.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  TORX_itra_df.groupby(['Status1', 'Year'])['Status1', 'Year'].count()

                     Status1  Year
Status1        Year
DNF            2018      345   345
               2019      378   378
               2021      281   281
               2023      472   472
               2024      552   552
Finished       2010      179   179
               2011      300   300
               2012       73    73
               2013      383   383
               2014      443   443
               2015        6     6
               2016      445   445
               2017      461   461
               2018      534   534
               2019      563   563
               2021      431   431
               2022      408   408
               2023      621   621
               2024      533   533
Race Cut Short 2012      319   319
               2015      467   467
               2022      182   182

In [13]:
# grabbing all finishers 
TORX_itra_df['Performance'] = TORX_itra_df['Performance'].astype('str')

TORX_itra_df = TORX_itra_df[[
    'Name', 'ITRA_Nationality', 'Sex',  'Age', 
    'Performance','Performance_Seconds','Status', 'Status1',
    'Race', 'Year'
]]
TORX_itra_df.to_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_itra_including_DNF.xlsx' , index = False)

In [28]:
TORX_itra_df[(TORX_itra_df['Year']=='2018')|
            (TORX_itra_df['Year']=='2019')|
            (TORX_itra_df['Year']=='2021')|
            (TORX_itra_df['Year']=='2022')|
            (TORX_itra_df['Year']=='2023')|
            (TORX_itra_df['Year']=='2014')].groupby(['Status1', 'Year'])['Status1' ].count().to_frame('count').reset_index()

           Status1  Year  count
0              DNF  2018    345
1              DNF  2019    378
2              DNF  2021    281
3              DNF  2023    472
4         Finished  2014    443
5         Finished  2018    534
6         Finished  2019    563
7         Finished  2021    431
8         Finished  2022    408
9         Finished  2023    621
10  Race Cut Short  2022    182

In [30]:
TORX_itra_2018_2024_including_df = TORX_itra_df[(TORX_itra_df['Year']=='2018')|
            (TORX_itra_df['Year']=='2019')|
            (TORX_itra_df['Year']=='2021')|
            (TORX_itra_df['Year']=='2022')|
            (TORX_itra_df['Year']=='2023')|
            (TORX_itra_df['Year']=='2014')]

In [31]:
TORX_itra_2018_2024_including_df.to_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_itra_2018_2024_including_df.xlsx' , index = False)

### Extracting only Finishers

In [14]:
# TORX_itra_df
TORX_itra_no_DNF = TORX_itra_df[(TORX_itra_df['Status1'] != 'DNF') 
                               ].reset_index(drop = True)
TORX_itra_no_DNF = TORX_itra_no_DNF[[
    'Name', 'ITRA_Nationality', 'Sex',  'Age', 
    'Performance','Performance_Seconds','Status','Status1', 
    'Race', 'Year'
]]

In [15]:
TORX_itra_no_DNF['Status1'].unique()

array(['Finished', 'Race Cut Short'], dtype=object)

In [16]:
TORX_itra_no_DNF.isna().sum()

Name                     0
ITRA_Nationality       659
Sex                     10
Age                    206
Performance              0
Performance_Seconds      0
Status                   0
Status1                  0
Race                     0
Year                     0
dtype: int64

In [17]:
TORX_itra_no_DNF.head()

,Name,ITRA_Nationality,Sex,Age,Performance,Performance_Seconds,Status,Status1,Race,Year
0,D Haene Francois,FRA,M,39,2 days 21:08:32,248912.0,Finished,Finished,TOR330,2024
1,Marmissolle Benat,FRA,M,43,3 days 01:10:18,263418.0,Finished,Finished,TOR330,2024
2,Perrier Martin,FRA,M,34,3 days 03:35:59,272159.0,Finished,Finished,TOR330,2024
3,Macchi Andrea,ITA,M,38,3 days 04:43:09,276189.0,Finished,Finished,TOR330,2024
4,Hall Damian,GBR,M,49,3 days 04:49:20,276560.0,Finished,Finished,TOR330,2024

In [18]:
TORX_itra_no_DNF.groupby(['Status1', 'Year'])['Status1', 'Year'].count()

C:\Users\Karina\AppData\Local\Temp\ipykernel_14208\2722326155.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  TORX_itra_no_DNF.groupby(['Status1', 'Year'])['Status1', 'Year'].count()

                     Status1  Year
Status1        Year
Finished       2010      179   179
               2011      300   300
               2012       73    73
               2013      383   383
               2014      443   443
               2015        6     6
               2016      445   445
               2017      461   461
               2018      534   534
               2019      563   563
               2021      431   431
               2022      408   408
               2023      621   621
               2024      533   533
Race Cut Short 2012      319   319
               2015      467   467
               2022      182   182

### This data might be used later data Visualisations

In [19]:
# grabbing all finishers 
TORX_itra_no_DNF['Performance'] = TORX_itra_no_DNF['Performance'].astype('str')

TORX_itra_no_DNF.to_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_itra_no_DNF.xlsx' , index = False)