In [1]:
import re
import pandas as pd
import time
import numpy as np
import matplotlib.pyplot as plt
import os
import seaborn as sns

### Reading in the Data

In [2]:
race = 'TOR330'

In [3]:
TOR330_dem = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_dem.xlsx')

In [4]:
TOR330_dem['Bib'][(TOR330_dem['Year'] == 2022) &
               (TOR330_dem['Retired'] == 'Bosses')].nunique()

0

In [5]:
TOR330_dem.groupby( ['Year','Status1'] )['Status1' ].count()

Year  Status1
2021  DNF                             286
      Finished at Courmayeur          431
2022  DNF                             363
      Finished at Bosses               88
      Finished at Courmayeur          408
      Finished at Rifugio Frassati    101
2023  DNF                             585
      Finished at Courmayeur          622
2024  DNF                             563
      Finished at Courmayeur          533
Name: Status1, dtype: int64

In [6]:
lifebase_cut_offs_df = pd.read_excel(f'{race} Data/4. TOR330 Timetable Data/{race}_lifebase_cut_offs_df.xlsx')

# # # Convert integer seconds to timedelta
lifebase_cut_offs_df['Lifebase Duration'] = pd.to_timedelta(lifebase_cut_offs_df['Lifebase Duration_seconds'], unit='s')

# # # Convert integer seconds to timedelta
lifebase_cut_offs_df['Running Total Lifebase Duration'] = pd.to_timedelta(lifebase_cut_offs_df['Running Total Lifebase Duration_seconds'], unit='s')

lifebase_cut_offs_df

,Lifebase,Stage,Lifebase Distance (km),Lifebase Accumulated Distance Elevation (m),Lifebase Elevation Gain (m),Lifebase Accumulated Elevation (m),Lifebase Duration_seconds,Running Total Lifebase Duration_seconds,Lifebase Duration,Running Total Lifebase Duration
0,Valgrisenche IN,Stage 1,48.55,48.55,4339,4339,68400.0,68400,0 days 19:00:00,0 days 19:00:00
1,Valgrisenche OUT,Time Spent in Valgrisenche,0.00,48.55,0,4339,7200.0,75600,0 days 02:00:00,0 days 21:00:00
2,Cogne IN,Stage 2,55.45,104.00,4943,9282,75600.0,151200,0 days 21:00:00,1 days 18:00:00
3,Cogne OUT,Time Spent in Cogne,0.00,104.00,0,9282,7200.0,158400,0 days 02:00:00,1 days 20:00:00
4,Donnas IN,Stage 3,45.77,149.77,2768,12050,64800.0,223200,0 days 18:00:00,2 days 14:00:00
5,Donnas OUT,Time Spent in Donnas,0.00,149.77,0,12050,7200.0,230400,0 days 02:00:00,2 days 16:00:00
6,Gressoney IN,Stage 4,54.23,204.00,5933,17983,75600.0,306000,0 days 21:00:00,3 days 13:00:00
7,Gressoney OUT,Time Spent in Gressoney,0.00,204.00,0,17983,7200.0,313200,0 days 02:00:00,3 days 15:00:00
8,Valtournenche IN,Stage 5,33.62,237.62,3094,21077,64800.0,378000,0 days 18:00:00,4 days 09:00:00
9,Valtournenche OUT,Time Spent in Valtournenche,0.00,237.62,0,21077,7200.0,385200,0 days 02:00:00,4 days 11:00:00
10,Ollomont IN,Stage 6,48.04,285.66,4625,25702,72000.0,457200,0 days 20:00:00,5 days 07:00:00
11,Ollomont OUT,Time Spent in Ollomont,0.00,285.66,0,25702,7200.0,464400,0 days 02:00:00,5 days 09:00:00
12,FINISH,Stage 7,49.66,335.32,3906,29608,75600.0,540000,0 days 21:00:00,6 days 06:00:00

In [7]:
checkpoints_bib_df = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_checkpoints_bib_df.xlsx')

In [8]:
all_aid_station_bib_df = pd.read_excel(f'TOR330 Data/5. Clean Data for Data Visualisation/TOR330_all_aid_station_bib_df.xlsx')

In [22]:
lifebase_bib_df = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_lifebase_bib_df.xlsx')

In [23]:
lifebase_bib_df = lifebase_bib_df.merge(
        TOR330_dem[['PK', 'Name','Status1']],
        on=['PK'],
        how='left')
lifebase_bib_df.head()

,PK,Year,Race,Bib,Wave,Lifebase,Stage,Timestamp,Duration_seconds,Running Total Duration_seconds,Banking Time_seconds,Missed Lifebase Allocated Time,Name,Status1
0,TOR330_2021_1,2021,TOR330,1,No Wave in 2021,Start,Stage 1,2021-09-12 10:00:00,NaN,0.0,NaN,Within Allocated Time,Colle Franco,Finished at Courmayeur
1,TOR330_2021_1,2021,TOR330,1,No Wave in 2021,Valgrisenche IN,Stage 1,2021-09-12 17:01:28,25288.0,25288.0,43112.0,Within Allocated Time,Colle Franco,Finished at Courmayeur
2,TOR330_2021_1,2021,TOR330,1,No Wave in 2021,Valgrisenche OUT,Time Spent in Valgrisenche,2021-09-12 17:02:49,81.0,25369.0,50231.0,Within Allocated Time,Colle Franco,Finished at Courmayeur
3,TOR330_2021_1,2021,TOR330,1,No Wave in 2021,Cogne IN,Stage 2,2021-09-13 02:55:10,35541.0,60910.0,90290.0,Within Allocated Time,Colle Franco,Finished at Courmayeur
4,TOR330_2021_1,2021,TOR330,1,No Wave in 2021,Cogne OUT,Time Spent in Cogne,2021-09-13 02:55:54,44.0,60954.0,97446.0,Within Allocated Time,Colle Franco,Finished at Courmayeur

In [32]:
# no_banking_df = lifebase_bib_df[(lifebase_bib_df['Status1'].str.contains( 'Courmayeur')) &
#                 (lifebase_bib_df['Lifebase'] != 'START') &
#                 (lifebase_bib_df['Banking Time_seconds'] <0)]

# no_banking_df['Banking Time_seconds'] = no_banking_df['Banking Time_seconds'].astype(int)
# # Apply function to the column
# no_banking_df['Banking Time'] =pd.to_timedelta(no_banking_df['Banking Time_seconds'], unit='s').astype(str)
no_banking_df['Running Total Duration'] =pd.to_timedelta(no_banking_df['Running Total Duration_seconds'], unit='s').astype(str)

for unique_name in no_banking_df['Name']:
    print(no_banking_df[['Name','Year', 'Race', 'Lifebase','Running Total Duration', 'Banking Time']][no_banking_df['Name'] == unique_name])
    print('*'*40)

C:\Users\Karina\AppData\Local\Temp\ipykernel_1020\2895392653.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  no_banking_df['Running Total Duration'] =pd.to_timedelta(no_banking_df['Running Total Duration_seconds'], unit='s').astype(str)

             Name  Year    Race           Lifebase Running Total Duration  \
4595  Cirla Marco  2021  TOR330           Cogne IN        1 days 18:59:19
4596  Cirla Marco  2021  TOR330          Cogne OUT        1 days 21:44:32
4600  Cirla Marco  2021  TOR330      Gressoney OUT        3 days 16:03:30
4602  Cirla Marco  2021  TOR330  Valtournenche OUT        4 days 11:38:56
4603  Cirla Marco  2021  TOR330        Ollomont IN        5 days 08:13:28

           Banking Time
4595  -1 days +23:00:41
4596  -1 days +22:15:28
4600  -1 days +22:56:30
4602  -1 days +23:21:04
4603  -1 days +22:46:32
****************************************
             Name  Year    Race           Lifebase Running Total Duration  \
4595  Cirla Marco  2021  TOR330           Cogne IN        1 days 18:59:19
4596  Cirla Marco  2021  TOR330          Cogne OUT        1 days 21:44:32
4600  Cirla Marco  2021  TOR330      Gressoney OUT        3 days 16:03:30
4602  Cirla Marco  2021  TOR330  Valtournenche OUT        4 days 11:38:56
4603  Cirla Marco  2021  TOR330        Ollomont IN        5 days 08:13:28

           Banking Time
4595  -1 days +23:00:41
4596  -1 days +22:15:28
4600  -1 days +22:56:30
4602  -1 days +23:21:04
4603  -1 days +22:46:32
****************************************
             Name  Year    Race           Lifebase Running Total Duration  \
4595  Cirla Marco  2021  TOR330           Cogne IN        1 days 18:59:19
4596  Cirla Marco  2021  TOR330          Cogne OUT        1 days 21:44:32
4600  Cirla Marco  2021  TOR330      Gressoney OUT        3 days 16:03:30
4602  Cirla Marco  2021  TOR330  Valtournenche OUT        4 days 11:38:56
4603  Cirla Marco  2021  TOR330        Ollomont IN        5 days 08:13:28

           Banking Time
4595  -1 days +23:00:41
4596  -1 days +22:15:28
4600  -1 days +22:56:30
4602  -1 days +23:21:04
4603  -1 days +22:46:32
****************************************
             Name  Year    Race           Lifebase Running Total Duration  \
4595  Cirla Marco  2021  TOR330           Cogne IN        1 days 18:59:19
4596  Cirla Marco  2021  TOR330          Cogne OUT        1 days 21:44:32
4600  Cirla Marco  2021  TOR330      Gressoney OUT        3 days 16:03:30
4602  Cirla Marco  2021  TOR330  Valtournenche OUT        4 days 11:38:56
4603  Cirla Marco  2021  TOR330        Ollomont IN        5 days 08:13:28

           Banking Time
4595  -1 days +23:00:41
4596  -1 days +22:15:28
4600  -1 days +22:56:30
4602  -1 days +23:21:04
4603  -1 days +22:46:32
****************************************
             Name  Year    Race           Lifebase Running Total Duration  \
4595  Cirla Marco  2021  TOR330           Cogne IN        1 days 18:59:19
4596  Cirla Marco  2021  TOR330          Cogne OUT        1 days 21:44:32
4600  Cirla Marco  2021  TOR330      Gressoney OUT        3 days 16:03:30
4602  Cirla Marco  2021  TOR330  Valtournenche OUT        4 days 11:38:56
4603  Cirla Marco  2021  TOR330        Ollomont IN        5 days 08:13:28

           Banking Time
4595  -1 days +23:00:41
4596  -1 days +22:15:28
4600  -1 days +22:56:30
4602  -1 days +23:21:04
4603  -1 days +22:46:32
****************************************
             Name  Year    Race       Lifebase Running Total Duration  \
4740  Rizzi Lucio  2021  TOR330  Gressoney OUT        3 days 15:22:43
4744  Rizzi Lucio  2021  TOR330   Ollomont OUT        5 days 09:21:58

           Banking Time
4740  -1 days +23:37:17
4744  -1 days +23:38:02
****************************************
             Name  Year    Race       Lifebase Running Total Duration  \
4740  Rizzi Lucio  2021  TOR330  Gressoney OUT        3 days 15:22:43
4744  Rizzi Lucio  2021  TOR330   Ollomont OUT        5 days 09:21:58

           Banking Time
4740  -1 days +23:37:17
4744  -1 days +23:38:02
****************************************
                   Name  Year    Race       Lifebase Running Total Duration  \
4894  Ntikiadis Ioannis  2021  TOR330  Gressoney OUT        3 days 15:10:17

           Banking Time
4894  -1 days +23:49:43
****************************************
                Name  Year    Race      Lifebase Running Total Duration  \
4982  Baglione Marco  2021  TOR330  Ollomont OUT        5 days 09:41:32

           Banking Time
4982  -1 days +23:18:28
****************************************
             Name  Year    Race      Lifebase Running Total Duration  \
5052  Holmes Bill  2021  TOR330  Ollomont OUT        5 days 09:03:52

           Banking Time
5052  -1 days +23:56:08
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5076  Watteyne Martin  2021  TOR330  Gressoney OUT        3 days 15:24:52
5080  Watteyne Martin  2021  TOR330   Ollomont OUT        5 days 09:06:54

           Banking Time
5076  -1 days +23:35:08
5080  -1 days +23:53:06
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5076  Watteyne Martin  2021  TOR330  Gressoney OUT        3 days 15:24:52
5080  Watteyne Martin  2021  TOR330   Ollomont OUT        5 days 09:06:54

           Banking Time
5076  -1 days +23:35:08
5080  -1 days +23:53:06
****************************************
               Name  Year    Race       Lifebase Running Total Duration  \
5090  Veyre Aurelia  2021  TOR330  Gressoney OUT        3 days 15:45:51
5094  Veyre Aurelia  2021  TOR330   Ollomont OUT        5 days 10:10:30

           Banking Time
5090  -1 days +23:14:09
5094  -1 days +22:49:30
****************************************
               Name  Year    Race       Lifebase Running Total Duration  \
5090  Veyre Aurelia  2021  TOR330  Gressoney OUT        3 days 15:45:51
5094  Veyre Aurelia  2021  TOR330   Ollomont OUT        5 days 10:10:30

           Banking Time
5090  -1 days +23:14:09
5094  -1 days +22:49:30
****************************************
                Name  Year    Race       Lifebase Running Total Duration  \
5174  Pizzorno Guido  2021  TOR330  Gressoney OUT        3 days 16:07:46
5178  Pizzorno Guido  2021  TOR330   Ollomont OUT        5 days 09:32:49

           Banking Time
5174  -1 days +22:52:14
5178  -1 days +23:27:11
****************************************
                Name  Year    Race       Lifebase Running Total Duration  \
5174  Pizzorno Guido  2021  TOR330  Gressoney OUT        3 days 16:07:46
5178  Pizzorno Guido  2021  TOR330   Ollomont OUT        5 days 09:32:49

           Banking Time
5174  -1 days +22:52:14
5178  -1 days +23:27:11
****************************************
                    Name  Year    Race       Lifebase Running Total Duration  \
5268  Cavallari Cristian  2021  TOR330      Cogne OUT        1 days 20:06:09
5272  Cavallari Cristian  2021  TOR330  Gressoney OUT        3 days 15:51:07

           Banking Time
5268  -1 days +23:53:51
5272  -1 days +23:08:53
****************************************
                    Name  Year    Race       Lifebase Running Total Duration  \
5268  Cavallari Cristian  2021  TOR330      Cogne OUT        1 days 20:06:09
5272  Cavallari Cristian  2021  TOR330  Gressoney OUT        3 days 15:51:07

           Banking Time
5268  -1 days +23:53:51
5272  -1 days +23:08:53
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5328  Nicolia Tiziana  2021  TOR330  Gressoney OUT        3 days 15:23:14

           Banking Time
5328  -1 days +23:36:46
****************************************
                 Name  Year    Race     Lifebase Running Total Duration  \
5345  Fabrice Gueriot  2021  TOR330  Ollomont IN        5 days 07:06:19

           Banking Time
5345  -1 days +23:53:41
****************************************
                Name  Year    Race       Lifebase Running Total Duration  \
5356  Yoshida Yosuke  2021  TOR330  Gressoney OUT        3 days 16:07:24

           Banking Time
5356  -1 days +22:52:36
****************************************
              Name  Year    Race       Lifebase Running Total Duration  \
5380  Cagna Andrea  2021  TOR330      Cogne OUT        1 days 20:15:59
5383  Cagna Andrea  2021  TOR330   Gressoney IN        3 days 13:20:27
5384  Cagna Andrea  2021  TOR330  Gressoney OUT        3 days 16:53:27

           Banking Time
5380  -1 days +23:44:01
5383  -1 days +23:39:33
5384  -1 days +22:06:33
****************************************

              Name  Year    Race       Lifebase Running Total Duration  \
5380  Cagna Andrea  2021  TOR330      Cogne OUT        1 days 20:15:59
5383  Cagna Andrea  2021  TOR330   Gressoney IN        3 days 13:20:27
5384  Cagna Andrea  2021  TOR330  Gressoney OUT        3 days 16:53:27

           Banking Time
5380  -1 days +23:44:01
5383  -1 days +23:39:33
5384  -1 days +22:06:33
****************************************
              Name  Year    Race       Lifebase Running Total Duration  \
5380  Cagna Andrea  2021  TOR330      Cogne OUT        1 days 20:15:59
5383  Cagna Andrea  2021  TOR330   Gressoney IN        3 days 13:20:27
5384  Cagna Andrea  2021  TOR330  Gressoney OUT        3 days 16:53:27

           Banking Time
5380  -1 days +23:44:01
5383  -1 days +23:39:33
5384  -1 days +22:06:33
****************************************
                  Name  Year    Race       Lifebase Running Total Duration  \
5394  Zanzottera Guido  2021  TOR330      Cogne OUT        1 days 20:15:47
5397  Zanzottera Guido  2021  TOR330   Gressoney IN        3 days 13:20:16
5398  Zanzottera Guido  2021  TOR330  Gressoney OUT        3 days 16:53:39

           Banking Time
5394  -1 days +23:44:13
5397  -1 days +23:39:44
5398  -1 days +22:06:21
****************************************
                  Name  Year    Race       Lifebase Running Total Duration  \
5394  Zanzottera Guido  2021  TOR330      Cogne OUT        1 days 20:15:47
5397  Zanzottera Guido  2021  TOR330   Gressoney IN        3 days 13:20:16
5398  Zanzottera Guido  2021  TOR330  Gressoney OUT        3 days 16:53:39

           Banking Time
5394  -1 days +23:44:13
5397  -1 days +23:39:44
5398  -1 days +22:06:21
****************************************
                  Name  Year    Race       Lifebase Running Total Duration  \
5394  Zanzottera Guido  2021  TOR330      Cogne OUT        1 days 20:15:47
5397  Zanzottera Guido  2021  TOR330   Gressoney IN        3 days 13:20:16
5398  Zanzottera Guido  2021  TOR330  Gressoney OUT        3 days 16:53:39

           Banking Time
5394  -1 days +23:44:13
5397  -1 days +23:39:44
5398  -1 days +22:06:21
****************************************
                                Name  Year    Race       Lifebase  \
5412  Matthiasdottir Proppe Halldora  2021  TOR330  Gressoney OUT
5415  Matthiasdottir Proppe Halldora  2021  TOR330    Ollomont IN
5416  Matthiasdottir Proppe Halldora  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5412        3 days 16:10:57  -1 days +22:49:03
5415        5 days 07:05:00  -1 days +23:55:00
5416        5 days 09:27:10  -1 days +23:32:50
****************************************
                                Name  Year    Race       Lifebase  \
5412  Matthiasdottir Proppe Halldora  2021  TOR330  Gressoney OUT
5415  Matthiasdottir Proppe Halldora  2021  TOR330    Ollomont IN
5416  Matthiasdottir Proppe Halldora  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5412        3 days 16:10:57  -1 days +22:49:03
5415        5 days 07:05:00  -1 days +23:55:00
5416        5 days 09:27:10  -1 days +23:32:50
****************************************
                                Name  Year    Race       Lifebase  \
5412  Matthiasdottir Proppe Halldora  2021  TOR330  Gressoney OUT
5415  Matthiasdottir Proppe Halldora  2021  TOR330    Ollomont IN
5416  Matthiasdottir Proppe Halldora  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5412        3 days 16:10:57  -1 days +22:49:03
5415        5 days 07:05:00  -1 days +23:55:00
5416        5 days 09:27:10  -1 days +23:32:50
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5454  Lodigiani Milko  2021  TOR330  Gressoney OUT        3 days 15:19:55
5457  Lodigiani Milko  2021  TOR330    Ollomont IN        5 days 07:04:57

           Banking Time
5454  -1 days +23:40:05
5457  -1 days +23:55:03
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5454  Lodigiani Milko  2021  TOR330  Gressoney OUT        3 days 15:19:55
5457  Lodigiani Milko  2021  TOR330    Ollomont IN        5 days 07:04:57

           Banking Time
5454  -1 days +23:40:05
5457  -1 days +23:55:03
****************************************
                  Name  Year    Race       Lifebase Running Total Duration  \
5468  Bianchi Federico  2021  TOR330  Gressoney OUT        3 days 15:21:12

           Banking Time
5468  -1 days +23:38:48
****************************************
              Name  Year    Race       Lifebase Running Total Duration  \
5492  Miserque Pol  2021  TOR330      Cogne OUT        1 days 20:11:18
5496  Miserque Pol  2021  TOR330  Gressoney OUT        3 days 16:21:18
5500  Miserque Pol  2021  TOR330   Ollomont OUT        5 days 09:21:10

           Banking Time
5492  -1 days +23:48:42
5496  -1 days +22:38:42
5500  -1 days +23:38:50
****************************************
              Name  Year    Race       Lifebase Running Total Duration  \
5492  Miserque Pol  2021  TOR330      Cogne OUT        1 days 20:11:18
5496  Miserque Pol  2021  TOR330  Gressoney OUT        3 days 16:21:18
5500  Miserque Pol  2021  TOR330   Ollomont OUT        5 days 09:21:10

           Banking Time
5492  -1 days +23:48:42
5496  -1 days +22:38:42
5500  -1 days +23:38:50
****************************************
              Name  Year    Race       Lifebase Running Total Duration  \
5492  Miserque Pol  2021  TOR330      Cogne OUT        1 days 20:11:18
5496  Miserque Pol  2021  TOR330  Gressoney OUT        3 days 16:21:18
5500  Miserque Pol  2021  TOR330   Ollomont OUT        5 days 09:21:10

           Banking Time
5492  -1 days +23:48:42
5496  -1 days +22:38:42
5500  -1 days +23:38:50
****************************************
                  Name  Year    Race       Lifebase Running Total Duration  \
5552  Legrand Virginie  2021  TOR330  Gressoney OUT        3 days 15:17:59

           Banking Time
5552  -1 days +23:42:01
****************************************
                  Name  Year    Race      Lifebase Running Total Duration  \
5584  Troussier Julien  2021  TOR330  Ollomont OUT        5 days 09:03:48

           Banking Time
5584  -1 days +23:56:12
****************************************
              Name  Year    Race       Lifebase Running Total Duration  \
5622  Gyalai Zsolt  2021  TOR330  Gressoney OUT        3 days 16:46:20
5625  Gyalai Zsolt  2021  TOR330    Ollomont IN        5 days 07:28:13
5626  Gyalai Zsolt  2021  TOR330   Ollomont OUT        5 days 09:28:17

           Banking Time
5622  -1 days +22:13:40
5625  -1 days +23:31:47
5626  -1 days +23:31:43
****************************************
              Name  Year    Race       Lifebase Running Total Duration  \
5622  Gyalai Zsolt  2021  TOR330  Gressoney OUT        3 days 16:46:20
5625  Gyalai Zsolt  2021  TOR330    Ollomont IN        5 days 07:28:13
5626  Gyalai Zsolt  2021  TOR330   Ollomont OUT        5 days 09:28:17

           Banking Time
5622  -1 days +22:13:40
5625  -1 days +23:31:47
5626  -1 days +23:31:43
****************************************
              Name  Year    Race       Lifebase Running Total Duration  \
5622  Gyalai Zsolt  2021  TOR330  Gressoney OUT        3 days 16:46:20
5625  Gyalai Zsolt  2021  TOR330    Ollomont IN        5 days 07:28:13
5626  Gyalai Zsolt  2021  TOR330   Ollomont OUT        5 days 09:28:17

           Banking Time
5622  -1 days +22:13:40
5625  -1 days +23:31:47
5626  -1 days +23:31:43
****************************************
                       Name  Year    Race      Lifebase  \
5640  Nicaise Jean Baptiste  2021  TOR330  Ollomont OUT

     Running Total Duration       Banking Time
5640        5 days 09:03:16  -1 days +23:56:44
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5650  Reichardt Frank  2021  TOR330  Gressoney OUT        3 days 15:54:50
5654  Reichardt Frank  2021  TOR330   Ollomont OUT        5 days 09:44:28

           Banking Time
5650  -1 days +23:05:10
5654  -1 days +23:15:32
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5650  Reichardt Frank  2021  TOR330  Gressoney OUT        3 days 15:54:50
5654  Reichardt Frank  2021  TOR330   Ollomont OUT        5 days 09:44:28

           Banking Time
5650  -1 days +23:05:10
5654  -1 days +23:15:32
****************************************
                      Name  Year    Race       Lifebase  \
5677  Nuzzi Pier Francesco  2021  TOR330   Gressoney IN
5678  Nuzzi Pier Francesco  2021  TOR330  Gressoney OUT
5681  Nuzzi Pier Francesco  2021  TOR330    Ollomont IN
5682  Nuzzi Pier Francesco  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5677        3 days 13:04:35  -1 days +23:55:25
5678        3 days 16:50:06  -1 days +22:09:54
5681        5 days 08:13:07  -1 days +22:46:53
5682        5 days 10:34:38  -1 days +22:25:22
****************************************
                      Name  Year    Race       Lifebase  \
5677  Nuzzi Pier Francesco  2021  TOR330   Gressoney IN
5678  Nuzzi Pier Francesco  2021  TOR330  Gressoney OUT
5681  Nuzzi Pier Francesco  2021  TOR330    Ollomont IN
5682  Nuzzi Pier Francesco  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5677        3 days 13:04:35  -1 days +23:55:25
5678        3 days 16:50:06  -1 days +22:09:54
5681        5 days 08:13:07  -1 days +22:46:53
5682        5 days 10:34:38  -1 days +22:25:22
****************************************
                      Name  Year    Race       Lifebase  \
5677  Nuzzi Pier Francesco  2021  TOR330   Gressoney IN
5678  Nuzzi Pier Francesco  2021  TOR330  Gressoney OUT
5681  Nuzzi Pier Francesco  2021  TOR330    Ollomont IN
5682  Nuzzi Pier Francesco  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5677        3 days 13:04:35  -1 days +23:55:25
5678        3 days 16:50:06  -1 days +22:09:54
5681        5 days 08:13:07  -1 days +22:46:53
5682        5 days 10:34:38  -1 days +22:25:22
****************************************
                      Name  Year    Race       Lifebase  \
5677  Nuzzi Pier Francesco  2021  TOR330   Gressoney IN
5678  Nuzzi Pier Francesco  2021  TOR330  Gressoney OUT
5681  Nuzzi Pier Francesco  2021  TOR330    Ollomont IN
5682  Nuzzi Pier Francesco  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5677        3 days 13:04:35  -1 days +23:55:25
5678        3 days 16:50:06  -1 days +22:09:54
5681        5 days 08:13:07  -1 days +22:46:53
5682        5 days 10:34:38  -1 days +22:25:22
****************************************
                              Name  Year    Race       Lifebase  \
5692  Benjumea Fernandez Francisco  2021  TOR330  Gressoney OUT
5696  Benjumea Fernandez Francisco  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5692        3 days 16:08:33  -1 days +22:51:27
5696        5 days 09:40:29  -1 days +23:19:31
****************************************
                              Name  Year    Race       Lifebase  \
5692  Benjumea Fernandez Francisco  2021  TOR330  Gressoney OUT
5696  Benjumea Fernandez Francisco  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5692        3 days 16:08:33  -1 days +22:51:27
5696        5 days 09:40:29  -1 days +23:19:31
****************************************
                      Name  Year    Race       Lifebase  \
5706  Hidalgo Vasco Javier  2021  TOR330  Gressoney OUT
5710  Hidalgo Vasco Javier  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5706        3 days 16:19:09  -1 days +22:40:51
5710        5 days 10:08:31  -1 days +22:51:29
****************************************
                      Name  Year    Race       Lifebase  \
5706  Hidalgo Vasco Javier  2021  TOR330  Gressoney OUT
5710  Hidalgo Vasco Javier  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5706        3 days 16:19:09  -1 days +22:40:51
5710        5 days 10:08:31  -1 days +22:51:29
****************************************
                              Name  Year    Race       Lifebase  \
5720  Carmona Marina Jose Fernando  2021  TOR330  Gressoney OUT
5724  Carmona Marina Jose Fernando  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5720        3 days 16:08:22  -1 days +22:51:38
5724        5 days 09:45:16  -1 days +23:14:44
****************************************

                              Name  Year    Race       Lifebase  \
5720  Carmona Marina Jose Fernando  2021  TOR330  Gressoney OUT
5724  Carmona Marina Jose Fernando  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5720        3 days 16:08:22  -1 days +22:51:38
5724        5 days 09:45:16  -1 days +23:14:44
****************************************
                  Name  Year    Race     Lifebase Running Total Duration  \
5737   Billi Francesca  2021  TOR330  Ollomont IN        5 days 07:02:30
47795  Billi Francesca  2024  TOR330       FINISH        6 days 06:53:20

            Banking Time
5737   -1 days +23:57:30
47795  -1 days +23:06:40
****************************************
                    Name  Year    Race      Lifebase Running Total Duration  \
5752  Bianchetto Stefano  2021  TOR330  Ollomont OUT        5 days 09:41:35

           Banking Time
5752  -1 days +23:18:25
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5762  Ricaldone Elena  2021  TOR330  Gressoney OUT        3 days 16:46:37
5766  Ricaldone Elena  2021  TOR330   Ollomont OUT        5 days 09:40:49

           Banking Time
5762  -1 days +22:13:23
5766  -1 days +23:19:11
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5762  Ricaldone Elena  2021  TOR330  Gressoney OUT        3 days 16:46:37
5766  Ricaldone Elena  2021  TOR330   Ollomont OUT        5 days 09:40:49

           Banking Time
5762  -1 days +22:13:23
5766  -1 days +23:19:11
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5776  Bolsi Francesco  2021  TOR330  Gressoney OUT        3 days 15:54:37
5780  Bolsi Francesco  2021  TOR330   Ollomont OUT        5 days 09:41:43

           Banking Time
5776  -1 days +23:05:23
5780  -1 days +23:18:17
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5776  Bolsi Francesco  2021  TOR330  Gressoney OUT        3 days 15:54:37
5780  Bolsi Francesco  2021  TOR330   Ollomont OUT        5 days 09:41:43

           Banking Time
5776  -1 days +23:05:23
5780  -1 days +23:18:17
****************************************
               Name  Year    Race       Lifebase Running Total Duration  \
5790  Polotti Diego  2021  TOR330  Gressoney OUT        3 days 15:23:02
5794  Polotti Diego  2021  TOR330   Ollomont OUT        5 days 09:08:28

           Banking Time
5790  -1 days +23:36:58
5794  -1 days +23:51:32
****************************************
               Name  Year    Race       Lifebase Running Total Duration  \
5790  Polotti Diego  2021  TOR330  Gressoney OUT        3 days 15:23:02
5794  Polotti Diego  2021  TOR330   Ollomont OUT        5 days 09:08:28

           Banking Time
5790  -1 days +23:36:58
5794  -1 days +23:51:32
****************************************
                         Name  Year    Race       Lifebase  \
5804  Fontana Giusti Giovanni  2021  TOR330  Gressoney OUT
5807  Fontana Giusti Giovanni  2021  TOR330    Ollomont IN
5808  Fontana Giusti Giovanni  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5804        3 days 15:45:12  -1 days +23:14:48
5807        5 days 07:26:27  -1 days +23:33:33
5808        5 days 10:09:05  -1 days +22:50:55
****************************************
                         Name  Year    Race       Lifebase  \
5804  Fontana Giusti Giovanni  2021  TOR330  Gressoney OUT
5807  Fontana Giusti Giovanni  2021  TOR330    Ollomont IN
5808  Fontana Giusti Giovanni  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5804        3 days 15:45:12  -1 days +23:14:48
5807        5 days 07:26:27  -1 days +23:33:33
5808        5 days 10:09:05  -1 days +22:50:55
****************************************
                         Name  Year    Race       Lifebase  \
5804  Fontana Giusti Giovanni  2021  TOR330  Gressoney OUT
5807  Fontana Giusti Giovanni  2021  TOR330    Ollomont IN
5808  Fontana Giusti Giovanni  2021  TOR330   Ollomont OUT

     Running Total Duration       Banking Time
5804        3 days 15:45:12  -1 days +23:14:48
5807        5 days 07:26:27  -1 days +23:33:33
5808        5 days 10:09:05  -1 days +22:50:55
****************************************
                    Name  Year    Race       Lifebase Running Total Duration  \
5831  Andersson Flemming  2021  TOR330   Gressoney IN        3 days 13:35:54
5832  Andersson Flemming  2021  TOR330  Gressoney OUT        3 days 16:53:51
5835  Andersson Flemming  2021  TOR330    Ollomont IN        5 days 07:43:57
5836  Andersson Flemming  2021  TOR330   Ollomont OUT        5 days 09:47:30

           Banking Time
5831  -1 days +23:24:06
5832  -1 days +22:06:09
5835  -1 days +23:16:03
5836  -1 days +23:12:30
****************************************
                    Name  Year    Race       Lifebase Running Total Duration  \
5831  Andersson Flemming  2021  TOR330   Gressoney IN        3 days 13:35:54
5832  Andersson Flemming  2021  TOR330  Gressoney OUT        3 days 16:53:51
5835  Andersson Flemming  2021  TOR330    Ollomont IN        5 days 07:43:57
5836  Andersson Flemming  2021  TOR330   Ollomont OUT        5 days 09:47:30

           Banking Time
5831  -1 days +23:24:06
5832  -1 days +22:06:09
5835  -1 days +23:16:03
5836  -1 days +23:12:30
****************************************
                    Name  Year    Race       Lifebase Running Total Duration  \
5831  Andersson Flemming  2021  TOR330   Gressoney IN        3 days 13:35:54
5832  Andersson Flemming  2021  TOR330  Gressoney OUT        3 days 16:53:51
5835  Andersson Flemming  2021  TOR330    Ollomont IN        5 days 07:43:57
5836  Andersson Flemming  2021  TOR330   Ollomont OUT        5 days 09:47:30

           Banking Time
5831  -1 days +23:24:06
5832  -1 days +22:06:09
5835  -1 days +23:16:03
5836  -1 days +23:12:30
****************************************
                    Name  Year    Race       Lifebase Running Total Duration  \
5831  Andersson Flemming  2021  TOR330   Gressoney IN        3 days 13:35:54
5832  Andersson Flemming  2021  TOR330  Gressoney OUT        3 days 16:53:51
5835  Andersson Flemming  2021  TOR330    Ollomont IN        5 days 07:43:57
5836  Andersson Flemming  2021  TOR330   Ollomont OUT        5 days 09:47:30

           Banking Time
5831  -1 days +23:24:06
5832  -1 days +22:06:09
5835  -1 days +23:16:03
5836  -1 days +23:12:30
****************************************
            Name  Year    Race       Lifebase Running Total Duration  \
5845  Bode Allan  2021  TOR330   Gressoney IN        3 days 13:36:09
5846  Bode Allan  2021  TOR330  Gressoney OUT        3 days 16:54:00
5849  Bode Allan  2021  TOR330    Ollomont IN        5 days 07:44:04
5850  Bode Allan  2021  TOR330   Ollomont OUT        5 days 09:47:15

           Banking Time
5845  -1 days +23:23:51
5846  -1 days +22:06:00
5849  -1 days +23:15:56
5850  -1 days +23:12:45
****************************************
            Name  Year    Race       Lifebase Running Total Duration  \
5845  Bode Allan  2021  TOR330   Gressoney IN        3 days 13:36:09
5846  Bode Allan  2021  TOR330  Gressoney OUT        3 days 16:54:00
5849  Bode Allan  2021  TOR330    Ollomont IN        5 days 07:44:04
5850  Bode Allan  2021  TOR330   Ollomont OUT        5 days 09:47:15

           Banking Time
5845  -1 days +23:23:51
5846  -1 days +22:06:00
5849  -1 days +23:15:56
5850  -1 days +23:12:45
****************************************
            Name  Year    Race       Lifebase Running Total Duration  \
5845  Bode Allan  2021  TOR330   Gressoney IN        3 days 13:36:09
5846  Bode Allan  2021  TOR330  Gressoney OUT        3 days 16:54:00
5849  Bode Allan  2021  TOR330    Ollomont IN        5 days 07:44:04
5850  Bode Allan  2021  TOR330   Ollomont OUT        5 days 09:47:15

           Banking Time
5845  -1 days +23:23:51
5846  -1 days +22:06:00
5849  -1 days +23:15:56
5850  -1 days +23:12:45
****************************************
            Name  Year    Race       Lifebase Running Total Duration  \
5845  Bode Allan  2021  TOR330   Gressoney IN        3 days 13:36:09
5846  Bode Allan  2021  TOR330  Gressoney OUT        3 days 16:54:00
5849  Bode Allan  2021  TOR330    Ollomont IN        5 days 07:44:04
5850  Bode Allan  2021  TOR330   Ollomont OUT        5 days 09:47:15

           Banking Time
5845  -1 days +23:23:51
5846  -1 days +22:06:00
5849  -1 days +23:15:56
5850  -1 days +23:12:45
****************************************
                  Name  Year    Race       Lifebase Running Total Duration  \
5860  Somoza Francisco  2021  TOR330  Gressoney OUT        3 days 16:49:43
5864  Somoza Francisco  2021  TOR330   Ollomont OUT        5 days 09:38:42

           Banking Time
5860  -1 days +22:10:17
5864  -1 days +23:21:18
****************************************
                  Name  Year    Race       Lifebase Running Total Duration  \
5860  Somoza Francisco  2021  TOR330  Gressoney OUT        3 days 16:49:43
5864  Somoza Francisco  2021  TOR330   Ollomont OUT        5 days 09:38:42

           Banking Time
5860  -1 days +22:10:17
5864  -1 days +23:21:18
****************************************
                  Name  Year    Race      Lifebase Running Total Duration  \
5878  Tordomar Marcelo  2021  TOR330  Ollomont OUT        5 days 09:37:32

           Banking Time
5878  -1 days +23:22:28
****************************************
               Name  Year    Race      Lifebase Running Total Duration  \
5891  Daniel Gloria  2021  TOR330   Ollomont IN        5 days 08:09:08
5892  Daniel Gloria  2021  TOR330  Ollomont OUT        5 days 10:20:49

           Banking Time
5891  -1 days +22:50:52
5892  -1 days +22:39:11
****************************************
               Name  Year    Race      Lifebase Running Total Duration  \
5891  Daniel Gloria  2021  TOR330   Ollomont IN        5 days 08:09:08
5892  Daniel Gloria  2021  TOR330  Ollomont OUT        5 days 10:20:49

           Banking Time
5891  -1 days +22:50:52
5892  -1 days +22:39:11
****************************************
                    Name  Year    Race           Lifebase  \
5902  Alexander Skrzypek  2021  TOR330      Gressoney OUT
5904  Alexander Skrzypek  2021  TOR330  Valtournenche OUT
5907  Alexander Skrzypek  2021  TOR330             FINISH

     Running Total Duration       Banking Time
5902        3 days 16:58:27  -1 days +22:01:33
5904        4 days 11:39:31  -1 days +23:20:29
5907        6 days 06:16:35  -1 days +23:43:25
****************************************
                    Name  Year    Race           Lifebase  \
5902  Alexander Skrzypek  2021  TOR330      Gressoney OUT
5904  Alexander Skrzypek  2021  TOR330  Valtournenche OUT
5907  Alexander Skrzypek  2021  TOR330             FINISH

     Running Total Duration       Banking Time
5902        3 days 16:58:27  -1 days +22:01:33
5904        4 days 11:39:31  -1 days +23:20:29
5907        6 days 06:16:35  -1 days +23:43:25
****************************************
                    Name  Year    Race           Lifebase  \
5902  Alexander Skrzypek  2021  TOR330      Gressoney OUT
5904  Alexander Skrzypek  2021  TOR330  Valtournenche OUT
5907  Alexander Skrzypek  2021  TOR330             FINISH

     Running Total Duration       Banking Time
5902        3 days 16:58:27  -1 days +22:01:33
5904        4 days 11:39:31  -1 days +23:20:29
5907        6 days 06:16:35  -1 days +23:43:25
****************************************
                    Name  Year    Race       Lifebase Running Total Duration  \
5915  Gambardella Cesare  2021  TOR330   Gressoney IN        3 days 13:05:47
5916  Gambardella Cesare  2021  TOR330  Gressoney OUT        3 days 16:46:08
5919  Gambardella Cesare  2021  TOR330    Ollomont IN        5 days 08:13:31
5920  Gambardella Cesare  2021  TOR330   Ollomont OUT        5 days 10:34:50
5921  Gambardella Cesare  2021  TOR330         FINISH        6 days 06:27:39

           Banking Time
5915  -1 days +23:54:13
5916  -1 days +22:13:52
5919  -1 days +22:46:29
5920  -1 days +22:25:10
5921  -1 days +23:32:21
****************************************
                    Name  Year    Race       Lifebase Running Total Duration  \
5915  Gambardella Cesare  2021  TOR330   Gressoney IN        3 days 13:05:47
5916  Gambardella Cesare  2021  TOR330  Gressoney OUT        3 days 16:46:08
5919  Gambardella Cesare  2021  TOR330    Ollomont IN        5 days 08:13:31
5920  Gambardella Cesare  2021  TOR330   Ollomont OUT        5 days 10:34:50
5921  Gambardella Cesare  2021  TOR330         FINISH        6 days 06:27:39

           Banking Time
5915  -1 days +23:54:13
5916  -1 days +22:13:52
5919  -1 days +22:46:29
5920  -1 days +22:25:10
5921  -1 days +23:32:21
****************************************
                    Name  Year    Race       Lifebase Running Total Duration  \
5915  Gambardella Cesare  2021  TOR330   Gressoney IN        3 days 13:05:47
5916  Gambardella Cesare  2021  TOR330  Gressoney OUT        3 days 16:46:08
5919  Gambardella Cesare  2021  TOR330    Ollomont IN        5 days 08:13:31
5920  Gambardella Cesare  2021  TOR330   Ollomont OUT        5 days 10:34:50
5921  Gambardella Cesare  2021  TOR330         FINISH        6 days 06:27:39

           Banking Time
5915  -1 days +23:54:13
5916  -1 days +22:13:52
5919  -1 days +22:46:29
5920  -1 days +22:25:10
5921  -1 days +23:32:21
****************************************
                    Name  Year    Race       Lifebase Running Total Duration  \
5915  Gambardella Cesare  2021  TOR330   Gressoney IN        3 days 13:05:47
5916  Gambardella Cesare  2021  TOR330  Gressoney OUT        3 days 16:46:08
5919  Gambardella Cesare  2021  TOR330    Ollomont IN        5 days 08:13:31
5920  Gambardella Cesare  2021  TOR330   Ollomont OUT        5 days 10:34:50
5921  Gambardella Cesare  2021  TOR330         FINISH        6 days 06:27:39

           Banking Time
5915  -1 days +23:54:13
5916  -1 days +22:13:52
5919  -1 days +22:46:29
5920  -1 days +22:25:10
5921  -1 days +23:32:21
****************************************
                    Name  Year    Race       Lifebase Running Total Duration  \
5915  Gambardella Cesare  2021  TOR330   Gressoney IN        3 days 13:05:47
5916  Gambardella Cesare  2021  TOR330  Gressoney OUT        3 days 16:46:08
5919  Gambardella Cesare  2021  TOR330    Ollomont IN        5 days 08:13:31
5920  Gambardella Cesare  2021  TOR330   Ollomont OUT        5 days 10:34:50
5921  Gambardella Cesare  2021  TOR330         FINISH        6 days 06:27:39

           Banking Time
5915  -1 days +23:54:13
5916  -1 days +22:13:52
5919  -1 days +22:46:29
5920  -1 days +22:25:10
5921  -1 days +23:32:21
****************************************
                Name  Year    Race      Lifebase Running Total Duration  \
5933  Manoni Giorgio  2021  TOR330   Ollomont IN        5 days 08:13:34
5934  Manoni Giorgio  2021  TOR330  Ollomont OUT        5 days 10:34:29
5935  Manoni Giorgio  2021  TOR330        FINISH        6 days 06:27:41

           Banking Time
5933  -1 days +22:46:26
5934  -1 days +22:25:31
5935  -1 days +23:32:19
****************************************
                Name  Year    Race      Lifebase Running Total Duration  \
5933  Manoni Giorgio  2021  TOR330   Ollomont IN        5 days 08:13:34
5934  Manoni Giorgio  2021  TOR330  Ollomont OUT        5 days 10:34:29
5935  Manoni Giorgio  2021  TOR330        FINISH        6 days 06:27:41

           Banking Time
5933  -1 days +22:46:26
5934  -1 days +22:25:31
5935  -1 days +23:32:19
****************************************

                Name  Year    Race      Lifebase Running Total Duration  \
5933  Manoni Giorgio  2021  TOR330   Ollomont IN        5 days 08:13:34
5934  Manoni Giorgio  2021  TOR330  Ollomont OUT        5 days 10:34:29
5935  Manoni Giorgio  2021  TOR330        FINISH        6 days 06:27:41

           Banking Time
5933  -1 days +22:46:26
5934  -1 days +22:25:31
5935  -1 days +23:32:19
****************************************
                 Name  Year    Race      Lifebase Running Total Duration  \
5947  Roques Frederic  2021  TOR330   Ollomont IN        5 days 07:32:52
5948  Roques Frederic  2021  TOR330  Ollomont OUT        5 days 09:31:43
5949  Roques Frederic  2021  TOR330        FINISH        6 days 06:29:49

           Banking Time
5947  -1 days +23:27:08
5948  -1 days +23:28:17
5949  -1 days +23:30:11
****************************************
                 Name  Year    Race      Lifebase Running Total Duration  \
5947  Roques Frederic  2021  TOR330   Ollomont IN        5 days 07:32:52
5948  Roques Frederic  2021  TOR330  Ollomont OUT        5 days 09:31:43
5949  Roques Frederic  2021  TOR330        FINISH        6 days 06:29:49

           Banking Time
5947  -1 days +23:27:08
5948  -1 days +23:28:17
5949  -1 days +23:30:11
****************************************
                 Name  Year    Race      Lifebase Running Total Duration  \
5947  Roques Frederic  2021  TOR330   Ollomont IN        5 days 07:32:52
5948  Roques Frederic  2021  TOR330  Ollomont OUT        5 days 09:31:43
5949  Roques Frederic  2021  TOR330        FINISH        6 days 06:29:49

           Banking Time
5947  -1 days +23:27:08
5948  -1 days +23:28:17
5949  -1 days +23:30:11
****************************************
                Name  Year    Race       Lifebase Running Total Duration  \
5958  Georgiana Popa  2021  TOR330  Gressoney OUT        3 days 16:20:30
5961  Georgiana Popa  2021  TOR330    Ollomont IN        5 days 08:36:59
5962  Georgiana Popa  2021  TOR330   Ollomont OUT        5 days 10:44:41
5963  Georgiana Popa  2021  TOR330         FINISH        6 days 06:30:05

           Banking Time
5958  -1 days +22:39:30
5961  -1 days +22:23:01
5962  -1 days +22:15:19
5963  -1 days +23:29:55
****************************************
                Name  Year    Race       Lifebase Running Total Duration  \
5958  Georgiana Popa  2021  TOR330  Gressoney OUT        3 days 16:20:30
5961  Georgiana Popa  2021  TOR330    Ollomont IN        5 days 08:36:59
5962  Georgiana Popa  2021  TOR330   Ollomont OUT        5 days 10:44:41
5963  Georgiana Popa  2021  TOR330         FINISH        6 days 06:30:05

           Banking Time
5958  -1 days +22:39:30
5961  -1 days +22:23:01
5962  -1 days +22:15:19
5963  -1 days +23:29:55
****************************************
                Name  Year    Race       Lifebase Running Total Duration  \
5958  Georgiana Popa  2021  TOR330  Gressoney OUT        3 days 16:20:30
5961  Georgiana Popa  2021  TOR330    Ollomont IN        5 days 08:36:59
5962  Georgiana Popa  2021  TOR330   Ollomont OUT        5 days 10:44:41
5963  Georgiana Popa  2021  TOR330         FINISH        6 days 06:30:05

           Banking Time
5958  -1 days +22:39:30
5961  -1 days +22:23:01
5962  -1 days +22:15:19
5963  -1 days +23:29:55
****************************************
                Name  Year    Race       Lifebase Running Total Duration  \
5958  Georgiana Popa  2021  TOR330  Gressoney OUT        3 days 16:20:30
5961  Georgiana Popa  2021  TOR330    Ollomont IN        5 days 08:36:59
5962  Georgiana Popa  2021  TOR330   Ollomont OUT        5 days 10:44:41
5963  Georgiana Popa  2021  TOR330         FINISH        6 days 06:30:05

           Banking Time
5958  -1 days +22:39:30
5961  -1 days +22:23:01
5962  -1 days +22:15:19
5963  -1 days +23:29:55
****************************************
                   Name  Year    Race       Lifebase Running Total Duration  \
5972  Scouflaire Helene  2021  TOR330  Gressoney OUT        3 days 16:57:02
5975  Scouflaire Helene  2021  TOR330    Ollomont IN        5 days 08:04:49
5976  Scouflaire Helene  2021  TOR330   Ollomont OUT        5 days 10:31:49
5977  Scouflaire Helene  2021  TOR330         FINISH        6 days 07:09:42

           Banking Time
5972  -1 days +22:02:58
5975  -1 days +22:55:11
5976  -1 days +22:28:11
5977  -1 days +22:50:18
****************************************
                   Name  Year    Race       Lifebase Running Total Duration  \
5972  Scouflaire Helene  2021  TOR330  Gressoney OUT        3 days 16:57:02
5975  Scouflaire Helene  2021  TOR330    Ollomont IN        5 days 08:04:49
5976  Scouflaire Helene  2021  TOR330   Ollomont OUT        5 days 10:31:49
5977  Scouflaire Helene  2021  TOR330         FINISH        6 days 07:09:42

           Banking Time
5972  -1 days +22:02:58
5975  -1 days +22:55:11
5976  -1 days +22:28:11
5977  -1 days +22:50:18
****************************************
                   Name  Year    Race       Lifebase Running Total Duration  \
5972  Scouflaire Helene  2021  TOR330  Gressoney OUT        3 days 16:57:02
5975  Scouflaire Helene  2021  TOR330    Ollomont IN        5 days 08:04:49
5976  Scouflaire Helene  2021  TOR330   Ollomont OUT        5 days 10:31:49
5977  Scouflaire Helene  2021  TOR330         FINISH        6 days 07:09:42

           Banking Time
5972  -1 days +22:02:58
5975  -1 days +22:55:11
5976  -1 days +22:28:11
5977  -1 days +22:50:18
****************************************
                   Name  Year    Race       Lifebase Running Total Duration  \
5972  Scouflaire Helene  2021  TOR330  Gressoney OUT        3 days 16:57:02
5975  Scouflaire Helene  2021  TOR330    Ollomont IN        5 days 08:04:49
5976  Scouflaire Helene  2021  TOR330   Ollomont OUT        5 days 10:31:49
5977  Scouflaire Helene  2021  TOR330         FINISH        6 days 07:09:42

           Banking Time
5972  -1 days +22:02:58
5975  -1 days +22:55:11
5976  -1 days +22:28:11
5977  -1 days +22:50:18
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5985  Pierrick Daniel  2021  TOR330   Gressoney IN        3 days 13:11:37
5986  Pierrick Daniel  2021  TOR330  Gressoney OUT        3 days 16:57:16
5989  Pierrick Daniel  2021  TOR330    Ollomont IN        5 days 08:15:47
5990  Pierrick Daniel  2021  TOR330   Ollomont OUT        5 days 10:50:34
5991  Pierrick Daniel  2021  TOR330         FINISH        6 days 07:09:42

           Banking Time
5985  -1 days +23:48:23
5986  -1 days +22:02:44
5989  -1 days +22:44:13
5990  -1 days +22:09:26
5991  -1 days +22:50:18
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5985  Pierrick Daniel  2021  TOR330   Gressoney IN        3 days 13:11:37
5986  Pierrick Daniel  2021  TOR330  Gressoney OUT        3 days 16:57:16
5989  Pierrick Daniel  2021  TOR330    Ollomont IN        5 days 08:15:47
5990  Pierrick Daniel  2021  TOR330   Ollomont OUT        5 days 10:50:34
5991  Pierrick Daniel  2021  TOR330         FINISH        6 days 07:09:42

           Banking Time
5985  -1 days +23:48:23
5986  -1 days +22:02:44
5989  -1 days +22:44:13
5990  -1 days +22:09:26
5991  -1 days +22:50:18
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5985  Pierrick Daniel  2021  TOR330   Gressoney IN        3 days 13:11:37
5986  Pierrick Daniel  2021  TOR330  Gressoney OUT        3 days 16:57:16
5989  Pierrick Daniel  2021  TOR330    Ollomont IN        5 days 08:15:47
5990  Pierrick Daniel  2021  TOR330   Ollomont OUT        5 days 10:50:34
5991  Pierrick Daniel  2021  TOR330         FINISH        6 days 07:09:42

           Banking Time
5985  -1 days +23:48:23
5986  -1 days +22:02:44
5989  -1 days +22:44:13
5990  -1 days +22:09:26
5991  -1 days +22:50:18
****************************************

                 Name  Year    Race       Lifebase Running Total Duration  \
5985  Pierrick Daniel  2021  TOR330   Gressoney IN        3 days 13:11:37
5986  Pierrick Daniel  2021  TOR330  Gressoney OUT        3 days 16:57:16
5989  Pierrick Daniel  2021  TOR330    Ollomont IN        5 days 08:15:47
5990  Pierrick Daniel  2021  TOR330   Ollomont OUT        5 days 10:50:34
5991  Pierrick Daniel  2021  TOR330         FINISH        6 days 07:09:42

           Banking Time
5985  -1 days +23:48:23
5986  -1 days +22:02:44
5989  -1 days +22:44:13
5990  -1 days +22:09:26
5991  -1 days +22:50:18
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
5985  Pierrick Daniel  2021  TOR330   Gressoney IN        3 days 13:11:37
5986  Pierrick Daniel  2021  TOR330  Gressoney OUT        3 days 16:57:16
5989  Pierrick Daniel  2021  TOR330    Ollomont IN        5 days 08:15:47
5990  Pierrick Daniel  2021  TOR330   Ollomont OUT        5 days 10:50:34
5991  Pierrick Daniel  2021  TOR330         FINISH        6 days 07:09:42

           Banking Time
5985  -1 days +23:48:23
5986  -1 days +22:02:44
5989  -1 days +22:44:13
5990  -1 days +22:09:26
5991  -1 days +22:50:18
****************************************
                       Name  Year    Race      Lifebase  \
6003  Rodrigues Paulo Jorge  2021  TOR330   Ollomont IN
6004  Rodrigues Paulo Jorge  2021  TOR330  Ollomont OUT
6005  Rodrigues Paulo Jorge  2021  TOR330        FINISH

     Running Total Duration       Banking Time
6003        5 days 07:41:51  -1 days +23:18:09
6004        5 days 09:52:44  -1 days +23:07:16
6005        6 days 07:33:21  -1 days +22:26:39
****************************************
                       Name  Year    Race      Lifebase  \
6003  Rodrigues Paulo Jorge  2021  TOR330   Ollomont IN
6004  Rodrigues Paulo Jorge  2021  TOR330  Ollomont OUT
6005  Rodrigues Paulo Jorge  2021  TOR330        FINISH

     Running Total Duration       Banking Time
6003        5 days 07:41:51  -1 days +23:18:09
6004        5 days 09:52:44  -1 days +23:07:16
6005        6 days 07:33:21  -1 days +22:26:39
****************************************
                       Name  Year    Race      Lifebase  \
6003  Rodrigues Paulo Jorge  2021  TOR330   Ollomont IN
6004  Rodrigues Paulo Jorge  2021  TOR330  Ollomont OUT
6005  Rodrigues Paulo Jorge  2021  TOR330        FINISH

     Running Total Duration       Banking Time
6003        5 days 07:41:51  -1 days +23:18:09
6004        5 days 09:52:44  -1 days +23:07:16
6005        6 days 07:33:21  -1 days +22:26:39
****************************************
              Name  Year    Race      Lifebase Running Total Duration  \
6018  Henrio Erick  2021  TOR330  Ollomont OUT        5 days 09:18:42
6019  Henrio Erick  2021  TOR330        FINISH        6 days 08:08:03

           Banking Time
6018  -1 days +23:41:18
6019  -1 days +21:51:57
****************************************
              Name  Year    Race      Lifebase Running Total Duration  \
6018  Henrio Erick  2021  TOR330  Ollomont OUT        5 days 09:18:42
6019  Henrio Erick  2021  TOR330        FINISH        6 days 08:08:03

           Banking Time
6018  -1 days +23:41:18
6019  -1 days +21:51:57
****************************************
               Name  Year    Race      Lifebase Running Total Duration  \
6031  Zanco Roberto  2021  TOR330   Ollomont IN        5 days 07:46:08
6032  Zanco Roberto  2021  TOR330  Ollomont OUT        5 days 10:27:36
6033  Zanco Roberto  2021  TOR330        FINISH        6 days 09:05:28

           Banking Time
6031  -1 days +23:13:52
6032  -1 days +22:32:24
6033  -1 days +20:54:32
****************************************
               Name  Year    Race      Lifebase Running Total Duration  \
6031  Zanco Roberto  2021  TOR330   Ollomont IN        5 days 07:46:08
6032  Zanco Roberto  2021  TOR330  Ollomont OUT        5 days 10:27:36
6033  Zanco Roberto  2021  TOR330        FINISH        6 days 09:05:28

           Banking Time
6031  -1 days +23:13:52
6032  -1 days +22:32:24
6033  -1 days +20:54:32
****************************************
               Name  Year    Race      Lifebase Running Total Duration  \
6031  Zanco Roberto  2021  TOR330   Ollomont IN        5 days 07:46:08
6032  Zanco Roberto  2021  TOR330  Ollomont OUT        5 days 10:27:36
6033  Zanco Roberto  2021  TOR330        FINISH        6 days 09:05:28

           Banking Time
6031  -1 days +23:13:52
6032  -1 days +22:32:24
6033  -1 days +20:54:32
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
28932  Nicoli Umberto  2023  TOR330  Gressoney OUT        3 days 15:02:33

            Banking Time
28932  -1 days +23:57:27
****************************************
                Name  Year    Race       Lifebase Running Total Duration  \
29660  Strand Monica  2023  TOR330  Gressoney OUT        3 days 15:07:06

            Banking Time
29660  -1 days +23:52:54
****************************************
              Name  Year    Race      Lifebase Running Total Duration  \
32114  Viizzo Mara  2023  TOR330  Ollomont OUT        5 days 09:00:42

            Banking Time
32114  -1 days +23:59:18
****************************************
                 Name  Year    Race Lifebase Running Total Duration  \
32171  Mondin Placido  2023  TOR330   FINISH        6 days 08:05:50

            Banking Time
32171  -1 days +21:54:10
****************************************
               Name  Year    Race Lifebase Running Total Duration  \
32185  Tibaldi Erik  2023  TOR330   FINISH        6 days 08:15:44

            Banking Time
32185  -1 days +21:44:16
****************************************
                 Name  Year    Race       Lifebase Running Total Duration  \
45774  Rawnsley Aaron  2024  TOR330  Gressoney OUT        3 days 15:06:37

            Banking Time
45774  -1 days +23:53:23
****************************************
                  Name  Year    Race      Lifebase Running Total Duration  \
47052  Praesi Suraroek  2024  TOR330  Ollomont OUT        5 days 09:07:06

            Banking Time
47052  -1 days +23:52:54
****************************************
                Name  Year    Race     Lifebase Running Total Duration  \
47219  Trimmer Jason  2024  TOR330  Ollomont IN        5 days 07:00:23

            Banking Time
47219  -1 days +23:59:37
****************************************
                Name  Year    Race       Lifebase Running Total Duration  \
47328  Beretta Marco  2024  TOR330  Gressoney OUT        3 days 15:00:18

            Banking Time
47328  -1 days +23:59:42
****************************************
                    Name  Year    Race      Lifebase Running Total Duration  \
47556  Kristavcnik Tomaz  2024  TOR330  Ollomont OUT        5 days 09:03:24

            Banking Time
47556  -1 days +23:56:36
****************************************
                Name  Year    Race       Lifebase Running Total Duration  \
47730  Zhang Jingang  2024  TOR330      Cogne OUT        1 days 20:30:30
47734  Zhang Jingang  2024  TOR330  Gressoney OUT        3 days 15:01:08
47738  Zhang Jingang  2024  TOR330   Ollomont OUT        5 days 09:04:16

            Banking Time
47730  -1 days +23:29:30
47734  -1 days +23:58:52
47738  -1 days +23:55:44
****************************************
                Name  Year    Race       Lifebase Running Total Duration  \
47730  Zhang Jingang  2024  TOR330      Cogne OUT        1 days 20:30:30
47734  Zhang Jingang  2024  TOR330  Gressoney OUT        3 days 15:01:08
47738  Zhang Jingang  2024  TOR330   Ollomont OUT        5 days 09:04:16

            Banking Time
47730  -1 days +23:29:30
47734  -1 days +23:58:52
47738  -1 days +23:55:44
****************************************
                Name  Year    Race       Lifebase Running Total Duration  \
47730  Zhang Jingang  2024  TOR330      Cogne OUT        1 days 20:30:30
47734  Zhang Jingang  2024  TOR330  Gressoney OUT        3 days 15:01:08
47738  Zhang Jingang  2024  TOR330   Ollomont OUT        5 days 09:04:16

            Banking Time
47730  -1 days +23:29:30
47734  -1 days +23:58:52
47738  -1 days +23:55:44
****************************************
                 Name  Year    Race      Lifebase Running Total Duration  \
47766  Bennett Sophie  2024  TOR330  Ollomont OUT        5 days 09:08:49

            Banking Time
47766  -1 days +23:51:11
****************************************

              Name  Year    Race Lifebase Running Total Duration  \
47781  Xi Hongpeng  2024  TOR330   FINISH        6 days 06:21:09

            Banking Time
47781  -1 days +23:38:51
****************************************
                  Name  Year    Race     Lifebase Running Total Duration  \
5737   Billi Francesca  2021  TOR330  Ollomont IN        5 days 07:02:30
47795  Billi Francesca  2024  TOR330       FINISH        6 days 06:53:20

            Banking Time
5737   -1 days +23:57:30
47795  -1 days +23:06:40
****************************************
             Name  Year    Race Lifebase Running Total Duration  \
47809  Lu Sheming  2024  TOR330   FINISH        6 days 06:57:12

            Banking Time
47809  -1 days +23:02:48
****************************************
               Name  Year    Race Lifebase Running Total Duration  \
47823  Zhang Bochao  2024  TOR330   FINISH        6 days 06:59:52

            Banking Time
47823  -1 days +23:00:08
****************************************
                        Name  Year    Race Lifebase Running Total Duration  \
47837  Forestiero Alessandro  2024  TOR330   FINISH        6 days 08:14:00

            Banking Time
47837  -1 days +21:46:00
****************************************

In [ ]:
# # making duration hours 
# datasets = [checkpoints_bib_df, lifebase_bib_df, all_aid_station_bib_df,  TOR330_dem]
# for df in datasets:
#     df['Duration_hours'] = df['Duration_seconds']/ 3600

In [ ]:
all_aid_station_bib_df

### Getting Average and Median time for lifebases

In [ ]:
Stage1 = [ 'Start', 'Baite Youlaz', 'La Thuile', 'Rifugio Deffeyes',\
          'Planaval', 'Valgrisenche IN']
Stage2 = [ 'Valgrisenche OUT', 'Chalet Epee',\
          'Rhemes-Notre-Dame', 'Eaux Rousse', 'Rifugio Sella', 'Cogne IN']
Stage3 = [  'Cogne OUT', 'Goilles', 'Rifugio Dondena', 'Chardonney', 'Pontboset','Donnas IN']
Stage4 = [  'Donnas OUT', 'Perloz', 'Sassa', 'Rifugio Coda', \
          'Rifugio della Barma', 'Lago Chiaro', 'Col della Vecchia',\
          'Niel La Gruba', 'Loo', 'Gressoney IN']
Stage5 = [  'Gressoney OUT', 'Rifugio Alpenzu', 'Champoluc' ,\
          'Rifugio Grand Tournalin', 'Valtournenche IN']
Stage6 = [   'Valtournenche OUT', 'Rifugio Barmasse', 'Vareton',\
          'Rifugio Magià', 'Rifugio Cuney', 'Bivacco R. Clermont', 'Oyace', \
          'Bruson Arp', 'Ollomont IN']    
Stage7 = [ 'Ollomont OUT', 'Rifugio Champillon', 'Ponteille Desot',\
          'Bosses', 'Rifugio Frassati', 'Pas Entre Deux Sauts',\
          'Monte de la Saxe', 'FINISH']


stages =[ Stage1, Stage2, Stage3, Stage4, Stage5, Stage6, Stage7]
stages_str =[ 'Stage 1', 'Stage 2', 'Stage 3', 'Stage 4', 'Stage 5', 'Stage 6', 'Stage 7']
lifebase_time_spent = ['Valgrisenche OUT','Cogne OUT','Donnas OUT','Gressoney OUT','Valtournenche OUT','Ollomont OUT']

In [ ]:
def creating_time_stats(df, column, category_order):
    
    df_merge = df.merge(
        TOR330_dem[['PK', 'Finish Category']],
        on=['PK'],
        how='left')


    df_merge['Duration_seconds'][df_merge['Duration_seconds']  <= 0] = np.nan

    stats_df = df_merge.groupby(['Finish Category', column])['Duration_seconds'].describe().reset_index(drop = False)


    stats_df[[ 'mean', 'std', 'min', '25%',
           '50%', '75%', 'max']] = stats_df[[ 'mean', 'std', 'min', '25%',
           '50%', '75%', 'max']].round(0)

    # Set 'Finish Category' as a categorical column with the defined order
    stats_df[column] = pd.Categorical(
        stats_df[column],
        categories=category_order,
        ordered=True)
    
    stats_df = stats_df.sort_values(by=column, ascending = True)
    
    

    for finish_category in df_merge['Finish Category'].unique():
        print(finish_category)
        stats_df.loc[
                (stats_df['Finish Category'] == finish_category), 'running_total_mean_seconds'
            ] =     stats_df.loc[
                (stats_df['Finish Category'] == finish_category), 'mean'
            ].cumsum()


        stats_df.loc[
                (stats_df['Finish Category'] == finish_category), 'running_total_median_seconds'
            ] =     stats_df.loc[
                (stats_df['Finish Category'] == finish_category), '50%'
            ].cumsum()


    stats_df = stats_df[['Finish Category', column,
            'count', 'mean', '50%', 'std', 'min', 'max', 
            'running_total_mean_seconds', 'running_total_median_seconds']]


    stats_df = stats_df.rename(columns={'count': f'Count_Finish_Category_{column}_seconds',
                                      'mean': f'Mean_Finish_Category_{column}_seconds',
                                      'std': f'STD_Finish_Category{column}t_seconds',
                                      '50%': f'Median_Finish_Category_{column}_seconds',
                                      'min': f'Min_Finish_Category_{column}_seconds', 
                                      'max': f'Max_Finish_Category_{column}_seconds'})
    stats_df = stats_df[stats_df[column] != 'Start']

    
    
    
    for stage,  stage_str in zip(stages, stages_str):
        stats_df.loc[stats_df[column].isin(stage), 'Stage'] = f'{stage_str}'
        
    for lifebase in lifebase_time_spent:
        lifebase_split = lifebase.split(' OUT')[0] 
        stats_df.loc[stats_df[column] == lifebase, 'Stage'] = f'Time Spent in {lifebase_split}'


    stats_df.to_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_{column}_duration_mean_median_stats_df.xlsx', index = False)

#     print(stats_df[stats_df['Finish Category'] == 'Sub-130'])
    return stats_df

In [ ]:
lifebase_stats_df = creating_time_stats(df = lifebase_bib_df, 
                    column = 'Lifebase', 
                    category_order = ['Start','Valgrisenche IN','Valgrisenche OUT',
                            'Cogne IN',  'Cogne OUT',
                            'Donnas IN', 'Donnas OUT', 
                            'Gressoney IN','Gressoney OUT',
                            'Valtournenche IN','Valtournenche OUT', 
                            'Ollomont IN','Ollomont OUT',
                            'FINISH'])

lifebase_stats_df

In [ ]:
# # # Convert integer seconds to timedelta
lifebase_stats_df['Median_Finish_Category_Lifebase'] = pd.to_timedelta(lifebase_stats_df['Median_Finish_Category_Lifebase_seconds'], unit='s')


lifebase_stats_df[['Finish Category','Lifebase', 'Median_Finish_Category_Lifebase']][lifebase_stats_df['Finish Category'] == 'Sub-130']

In [ ]:
checkpoints_stats_df = creating_time_stats(df = checkpoints_bib_df, 
                    column = 'Checkpoint', 
                    category_order = ['La Thuile', 'Valgrisenche IN', 'Valgrisenche OUT',
                                       'Eaux Rousse', 'Cogne IN', 'Cogne OUT', 'Donnas IN', 'Donnas OUT',
                                       'Rifugio della Barma', 'Niel La Gruba', 'Gressoney IN',
                                       'Gressoney OUT', 'Champoluc', 'Valtournenche IN',
                                       'Valtournenche OUT', 'Oyace', 'Ollomont IN', 'Ollomont OUT',
                                       'FINISH'])

checkpoints_stats_df

In [ ]:
# all_aid_station_bib_stats_df = creating_time_stats(df = all_aid_station_bib_df, 
#                     column = 'Aid Station', 
#                     category_order = ['Baite Youlaz', 'La Thuile', 'Rifugio Deffeyes',
#                                    'Planaval', 'Valgrisenche IN', 'Valgrisenche OUT', 'Chalet Epee',
#                                    'Rhemes-Notre-Dame', 'Eaux Rousse', 'Rifugio Sella', 'Cogne IN',
#                                    'Cogne OUT', 'Goilles', 'Rifugio Dondena', 'Chardonney', 'Pontboset',
#                                    'Donnas IN', 'Donnas OUT', 'Perloz', 'Sassa', 'Rifugio Coda',
#                                    'Rifugio della Barma', 'Lago Chiaro', 'Col della Vecchia',
#                                    'Niel La Gruba', 'Loo', 'Gressoney IN', 'Gressoney OUT',
#                                    'Rifugio Alpenzu', 'Champoluc', 'Rifugio Grand Tournalin',
#                                    'Valtournenche IN', 'Valtournenche OUT', 'Rifugio Barmasse', 'Vareton',
#                                    'Rifugio Magià', 'Rifugio Cuney', 'Bivacco R. Clermont', 'Oyace',
#                                    'Bruson Arp', 'Ollomont IN', 'Ollomont OUT', 'Rifugio Champillon',
#                                    'Ponteille Desot', 'Bosses', 'Rifugio Frassati', 'Pas Entre Deux Sauts',
#                                    'Monte de la Saxe', 'FINISH'])

# all_aid_station_bib_stats_df

### Who ran too easy or hard at the start?

In [ ]:
# sub_TOR330_dem_bib_list = list(TOR330_dem['PK'][TOR330_dem['Finish Category'] == 'Sub-130'].unique())

# new_bib_list = []
# for bib in sub_TOR330_dem_bib_list:
#     df = lifebase_bib_df[
#                 ((lifebase_bib_df['Duration_hours']> 14) &
#                 (lifebase_bib_df['Lifebase'] == 'Valgrisenche IN') )
#     &
#                 (lifebase_bib_df['PK']== bib)
#                ]
    
#     new_bib_list.append(df)
# df= pd.concat(new_bib_list)
# pk_unique = list(df['PK'].unique())

# for pk in pk_unique:
#     print(lifebase_bib_df[['PK','Lifebase', 'Timestamp', 'Duration_hours']][(lifebase_bib_df['PK'] == pk)  ], '\n', '*'*40,  '\n',)
#     print(TOR330_dem[['PK', 'Finish Category', 'Duration_hours']][(TOR330_dem['PK'] == pk)  ], '\n','\n','\n','\n', '*'*40,  '\n',)

In [ ]:
# sub_TOR330_dem_bib_list = list(TOR330_dem['PK'][TOR330_dem['Finish Category'] == 'Sub-140'].unique())

# new_bib_list = []
# for bib in sub_TOR330_dem_bib_list:
#     df = lifebase_bib_df[
#                 ((lifebase_bib_df['Duration_hours']< 10) &
#                 (lifebase_bib_df['Lifebase'] == 'Valgrisenche IN') ) &
#                 (lifebase_bib_df['PK']== bib)]
#     new_bib_list.append(df)
    
# df= pd.concat(new_bib_list)

# pk_unique = list(df['PK'].unique())

# for pk in pk_unique:
#     print(lifebase_bib_df[['PK', 'Wave', 'Lifebase', 'Duration_hours']][(lifebase_bib_df['PK'] == pk)  ], '\n', '\n',)
#     print(TOR330_dem[['PK', 'Finish Category', 'Duration_hours']][(TOR330_dem['PK'] == pk)  ], '\n', '*'*40,  '\n',)

In [ ]:
# # reading in Raw Data
# races = ['TOR330']
# years = [ 
# #     '2021',
# #         '2022',
# #          '2023', 
#     '2024'
#         ]

# TORX_df = {}

# for race in races:
#     for year in years:
#         df = pd.read_excel(f'{race} Data/1. 100x100trail/{race}_{year}.xlsx',
#                                  dtype={'Start Date': 'string',
#                                         'Year': 'string'})
#         print(f'{race}_{year} {df.shape}')
#         # Store the DataFrame in the dictionary with a key like 'TOR330_2021'
#         TORX_df[f'{race}_{year}'] = df
#     print('*'*50)
    
# TORX_df_concat = pd.concat(TORX_df)
# TOR330 = TORX_df_concat[TORX_df_concat['Year'] == year]

In [ ]:
# sub_TOR330_dem_bib_list = list(TOR330_dem['PK'][TOR330_dem['Finish Category'] == 'Sub-90'].unique())

# new_bib_list = []
# for bib in sub_TOR330_dem_bib_list:
#     df = lifebase_bib_df[
#                 ((lifebase_bib_df['Duration_hours']> 8) &
#                 (lifebase_bib_df['Lifebase'] == 'Valgrisenche OUT') ) &
#                 (lifebase_bib_df['PK']== bib)]
#     new_bib_list.append(df)
    
# df= pd.concat(new_bib_list)

# pk_unique = list(df['PK'].unique())

# for pk in pk_unique:
#     print(lifebase_bib_df[['PK', 'Wave', 'Lifebase', 'Duration_hours']][(lifebase_bib_df['PK'] == pk)  ], '\n', '\n',)
#     print(TOR330_dem[['PK', 'Finish Category', 'Duration_hours']][(TOR330_dem['PK'] == pk)  ], '\n', '*'*40,  '\n',)