import pandas as pd
import numpy as np
import re

In [2]:
race = 'TOR330'

In [3]:
TOR330_itra_2018_2019_including_DNF_df = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_itra_2018_2019_including_DNFs_df.xlsx' )
TOR330_dem = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_dem.xlsx' )

In [4]:
TOR330_dem = TOR330_dem[ ['Year', 'Race', 'Name', 'Sex', 'Nationality', 'Category',
       'Status', 'Status1','Duration_seconds','Finish Category']]

In [5]:
TOR330_itra_2018_2019_including_DNF_df[['Race', 'Year', 'Name', 'ITRA_Nationality', 'Sex', 'Age Category', 'Performance',
       'Performance_Seconds', 'Status', 'Status1']]

,Race,Year,Name,ITRA_Nationality,Sex,Age Category,Performance,Performance_Seconds,Status,Status1
0,TOR330,2019,Bosatelli Oliviero,ITA,M,V2,3 days 00:37:13,261433.0,Finished,Finished
1,TOR330,2019,Reynolds Galen,CAN,M,SEN,3 days 05:06:12,277572.0,Finished,Finished
2,TOR330,2019,Lantermino Danilo,ITA,M,SEN,3 days 07:09:46,284986.0,Finished,Finished
3,TOR330,2019,Erwee Tiaan,RSA,M,SEN,3 days 08:18:24,289104.0,Finished,Finished
4,TOR330,2019,Lukas Jens,GER,M,V2,3 days 13:04:04,306244.0,Finished,Finished
...,...,...,...,...,...,...,...,...,...,...
1815,TOR330,2018,Zdon Bill,USA,M,SEN,NaT,NaN,DNF,DNF
1816,TOR330,2018,Zennaro Davide,ITA,M,V2,NaT,NaN,DNF,DNF
1817,TOR330,2018,Zimei Andrea,ITA,M,SEN,NaT,NaN,DNF,DNF
1818,TOR330,2018,Zimmermann Denise,SUI,F,V1,NaT,NaN,DNF,DNF
1819,TOR330,2018,Zugna Davide,ITA,M,V1,NaT,NaN,DNF,DNF

In [6]:

# Create a new column 'Finish Category'
def categorize_duration(hours):
    if hours < 60:
        return 'Sub-60'
    elif hours <= 150:
        return f'{int(hours // 10) * 10}-{int(hours // 10) * 10+9}'  # Round to nearest 10 up to 150
    else:
        return 'Over-150'
    
# Define the desired order of categories
finish_category_order = [
    'Sub-60', '60-69',
    '70-79','80-89','90-99', '100-109', '110-119', '120-129',
    '130-139', '140-149',  'Over-150']
    
TOR330_itra_2018_2019_including_DNF_df  = TOR330_itra_2018_2019_including_DNF_df.rename(columns={"Performance": "Duration",
                                                    "Performance_Seconds": "Duration_seconds",
                                                    "ITRA_Nationality": "Nationality",
                                                "Age Category": "Category",
                                                   }) 
TOR330_itra_2018_2019_including_DNF_df ['Status'] = TOR330_itra_2018_2019_including_DNF_df ['Status'].str.replace('Finished', 'Finished at Courmayeur')
TOR330_itra_2018_2019_including_DNF_df ['Status1'] = TOR330_itra_2018_2019_including_DNF_df ['Status'].copy() 

TOR330_itra_2018_2019_including_DNF_df .loc[TOR330_itra_2018_2019_including_DNF_df ['Status1'] == 'Finished at Courmayeur', 'Status'] = 'True'
TOR330_itra_2018_2019_including_DNF_df .loc[TOR330_itra_2018_2019_including_DNF_df ['Status1'] == 'DNF', 'Status'] = 'False'

# Convert to timedelta and get total hours (handling NaT)
TOR330_itra_2018_2019_including_DNF_df ['Duration_hours'] = pd.to_timedelta(
    TOR330_itra_2018_2019_including_DNF_df ['Duration'], errors='coerce'
).dt.total_seconds() / 3600  # Convert seconds to hours



TOR330_itra_2018_2019_including_DNF_df ['Finish Category'] = TOR330_itra_2018_2019_including_DNF_df ['Duration_hours'].apply(categorize_duration)


# Set 'Finish Category' as a categorical column with the defined order
TOR330_itra_2018_2019_including_DNF_df ['Finish Category'] = pd.Categorical(
    TOR330_itra_2018_2019_including_DNF_df ['Finish Category'],
    categories = finish_category_order,
    ordered = True
)

In [7]:
# def categorize_age(age):
#     if age < 40: # under40
#         return 'SEN'
#     elif age < 50: #40-49
#         return 'V1'
#     elif age < 60: #50-59
#         return 'V2'
#     elif age < 70: #60-69
#         return 'V3'
#     elif age >= 70:
#         return 'V4' # Over 70
#     else:
#         return '-'

# TOR330_itra_2018_2019_including_DNF_df['Age'] = TOR330_itra_2018_2019_including_DNF_df['Age'].str.replace('-', '0')
# TOR330_itra_2018_2019_including_DNF_df['Age'] = TOR330_itra_2018_2019_including_DNF_df['Age'].astype(int)

# TOR330_itra_2018_2019_including_DNF_df ['AgeCategory'] = TOR330_itra_2018_2019_including_DNF_df['Age'].apply(categorize_age)

In [8]:

TOR330_itra_2018_2019_including_DNF_df.loc[TOR330_itra_2018_2019_including_DNF_df['Status1'] == 'True', 'Status1']  = 'Finished at Courmayeur'

TOR330_itra_2018_2019_including_DNF_df.loc[TOR330_itra_2018_2019_including_DNF_df['Status1'] == 'False', 'Status1']  = 'DNFs'

In [9]:

TOR330_itra_2018_2019_including_DNF_df  = TOR330_itra_2018_2019_including_DNF_df [[
    'Race','Year',  'Name',  'Sex', 'Nationality','Category',
       'Status', 'Status1',  'Duration_hours', 'Duration_seconds', 'Finish Category']]

TOR330_itra_2018_2019_including_DNF_df.head()

,Race,Year,Name,Sex,Nationality,Category,Status,Status1,Duration_hours,Duration_seconds,Finish Category
0,TOR330,2019,Bosatelli Oliviero,M,ITA,V2,True,Finished at Courmayeur,72.620278,261433.0,70-79
1,TOR330,2019,Reynolds Galen,M,CAN,SEN,True,Finished at Courmayeur,77.103333,277572.0,70-79
2,TOR330,2019,Lantermino Danilo,M,ITA,SEN,True,Finished at Courmayeur,79.162778,284986.0,70-79
3,TOR330,2019,Erwee Tiaan,M,RSA,SEN,True,Finished at Courmayeur,80.306667,289104.0,80-89
4,TOR330,2019,Lukas Jens,M,GER,V2,True,Finished at Courmayeur,85.067778,306244.0,80-89

In [10]:

# Mapping of 3-letter to 2-letter country codes
country_mapping = {
    ' ITA': 'IT', ' CAN': 'CA', ' RSA': 'ZA', ' GER': 'DE', ' ESP': 'ES', ' ROU': 'RO', ' FRA': 'FR', ' USA': 'US',
    ' GBR': 'GB', ' FIN': 'FI', ' CZE': 'CZ', ' CHN': 'CN', ' JPN': 'JP', ' CRO': 'HR', ' NOR': 'NO', ' BEL': 'BE',
    ' SUI': 'CH', ' COL': 'CO', ' AUS': 'AU', ' POR': 'PT', ' UKR': 'UA', ' HUN': 'HU', ' SLO': 'SI', ' SWE': 'SE',
    ' ISL': 'IS', ' BUL': 'BG', ' ARG': 'AR', ' MEX': 'MX', ' CRC': 'CR', ' NED': 'NL', ' IND': 'IN', ' NZL': 'NZ',
    ' DEN': 'DK', ' ECU': 'EC', ' BRA': 'BR', ' LTU': 'LT', ' TUR': 'TR', ' POL': 'PL', ' TPE': 'TW', ' SRB': 'RS',
    ' GRE': 'GR', ' AND': 'AD', ' SVK': 'SK', ' KOR': 'KR', ' RUS': 'RU', ' AUT': 'AT', ' MAS': 'MY', ' PHI': 'PH',
    ' SGP': 'SG', ' KEN': 'KE', ' HKG': 'HK', ' CHE': 'CH', ' MAC': 'MO', ' LBN': 'LB', ' THA': 'TH', ' INA': 'ID',
    ' MAD': 'MG', ' VIE': 'VN', ' IRL': 'IE', ' MDA': 'MD', ' CHI': 'CL', ' MON': 'MC', ' URU': 'UY', ' QAT': 'QA',
    ' PER': 'PE', ' MNE': 'ME', ' LUX': 'LU', ' ESA': 'SV', ' ISR': 'IL', ' BRU': 'BN', ' AFG': 'AF'
}

# Apply the mapping
TOR330_itra_2018_2019_including_DNF_df['Nationality'] = TOR330_itra_2018_2019_including_DNF_df['Nationality'].replace(country_mapping)

# Display updated DataFrame
print(TOR330_itra_2018_2019_including_DNF_df)

        Race  Year                Name Sex Nationality Category Status  \
0     TOR330  2019  Bosatelli Oliviero   M          IT       V2   True
1     TOR330  2019      Reynolds Galen   M          CA      SEN   True
2     TOR330  2019   Lantermino Danilo   M          IT      SEN   True
3     TOR330  2019         Erwee Tiaan   M          ZA      SEN   True
4     TOR330  2019          Lukas Jens   M          DE       V2   True
...      ...   ...                 ...  ..         ...      ...    ...
1815  TOR330  2018           Zdon Bill   M          US      SEN  False
1816  TOR330  2018      Zennaro Davide   M          IT       V2  False
1817  TOR330  2018        Zimei Andrea   M          IT      SEN  False
1818  TOR330  2018   Zimmermann Denise   F          CH       V1  False
1819  TOR330  2018        Zugna Davide   M          IT       V1  False

                     Status1  Duration_hours  Duration_seconds Finish Category
0     Finished at Courmayeur       72.620278          261433.0           70-79
1     Finished at Courmayeur       77.103333          277572.0           70-79
2     Finished at Courmayeur       79.162778          284986.0           70-79
3     Finished at Courmayeur       80.306667          289104.0           80-89
4     Finished at Courmayeur       85.067778          306244.0           80-89
...                      ...             ...               ...             ...
1815                     DNF             NaN               NaN        Over-150
1816                     DNF             NaN               NaN        Over-150
1817                     DNF             NaN               NaN        Over-150
1818                     DNF             NaN               NaN        Over-150
1819                     DNF             NaN               NaN        Over-150

[1820 rows x 11 columns]

In [11]:
for nationality in TOR330_itra_2018_2019_including_DNF_df['Nationality'].unique():
    if len(nationality) !=2:
        print(nationality)
#         print(f'TOR330_itra_2018_2019_including_DNF_df.loc[TOR330_itra_2018_2019_including_DNF_df[\'Nationality\'] == \'{nationality}\', \'Nationality\'] == \'\'')

In [12]:
TOR330_dem['Year'] =TOR330_dem['Year'].astype(str)
TOR330_itra_2018_2019_including_DNF_df['Year'] =TOR330_itra_2018_2019_including_DNF_df['Year'].astype(str)

In [13]:
TOR330_itra_2018_2019_including_DNF_df['Year'].unique()

array(['2019', '2018'], dtype=object)

In [14]:
# Concatenate along columns (axis=1)
TOR330_dem_2018_2024 = pd.concat([TOR330_dem, TOR330_itra_2018_2019_including_DNF_df])

# Set 'Finish Category' as a categorical column with the defined order
TOR330_dem_2018_2024['Year'] = pd.Categorical(
    TOR330_dem_2018_2024['Year'],
    categories = ['2018','2019',  '2021', '2022', '2023', '2024'],
    ordered = True
)


TOR330_dem_2018_2024['Year'].unique()

['2021', '2022', '2023', '2024', '2019', '2018']
Categories (6, object): ['2018' < '2019' < '2021' < '2022' < '2023' < '2024']

In [15]:
n = 0

nationality_df = []
for name in list(TOR330_dem_2018_2024['Name'].unique()):
    name_df = TOR330_dem_2018_2024[TOR330_dem_2018_2024['Name'] == name]
    if len(list(name_df['Year'].unique())) == 1:
#         print(name_df['Name'].unique())
        n = n+1
#         print(n, name_df['Name'].unique(), name_df['Nationality'].unique())
        nationality_df.append(name_df)
    else:
        name_df.loc[name_df['Year'] == '2019', 'Nationality'] = np.nan
        name_df['Nationality'] = name_df['Nationality'].bfill()
        nationality_df.append(name_df)
        
TOR330_dem_2018_2024_1= pd.concat(nationality_df)

TOR330_dem_2018_2024_1[TOR330_dem_2018_2024_1['Name'] == 'Papi Luca'].reset_index(drop = True)

C:\Users\Karina\AppData\Local\Temp\ipykernel_22320\3552628193.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  name_df['Nationality'] = name_df['Nationality'].bfill()

Empty DataFrame
Columns: [Year, Race, Name, Sex, Nationality, Category, Status, Status1, Duration_seconds, Finish Category, Duration_hours]
Index: []

In [21]:
TOR330_dem_2018_2024_1.groupby([ 'Year', 'Status1'])['Status1'].count()

Year  Status1
2018  DNF                                       345
      Finished at Bosses or Rifugio Frassati      0
      Finished at Courmayeur                    534
2019  DNF                                       378
      Finished at Bosses or Rifugio Frassati      0
      Finished at Courmayeur                    563
2021  DNF                                       281
      Finished at Bosses or Rifugio Frassati      0
      Finished at Courmayeur                    431
2022  DNF                                       363
      Finished at Bosses or Rifugio Frassati    189
      Finished at Courmayeur                    408
2023  DNF                                       584
      Finished at Bosses or Rifugio Frassati      0
      Finished at Courmayeur                    857
2024  DNF                                       562
      Finished at Bosses or Rifugio Frassati      0
      Finished at Courmayeur                    533
Name: Status1, dtype: int64

In [17]:
TOR330_dem_2018_2024_1['Status1'] =TOR330_dem_2018_2024_1['Status1'].str.replace('Finished at Bosses','Finished at Bosses or Rifugio Frassati') 
TOR330_dem_2018_2024_1['Status1'] =TOR330_dem_2018_2024_1['Status1'].str.replace('Finished at Rifugio Frassati','Finished at Bosses or Rifugio Frassati')

In [19]:
TOR330_dem_2018_2024_1 = TOR330_dem_2018_2024_1[['Year', 'Race', 'Name', 'Sex', 'Nationality', 'Category', 'Status',
       'Status1', 'Duration_seconds', 'Finish Category', 'Duration_hours']].drop_duplicates()

In [20]:
TOR330_dem_2018_2024_1.to_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_dem_2018_2024.xlsx', index = False)

In [ ]:
TOR330_dem_2018_2024_1['Sex'].unique()